composer.json
composer.lock
html/themes/custom/common_design_subtheme/components/README.md
html/themes/custom/common_design_subtheme/components/cd-language-switcher/README.md
html/themes/custom/common_design_subtheme/components/cd-language-switcher/cd-language-switcher.css
html/themes/custom/common_design_subtheme/package-lock.json
patches/common_design-drupal-10-compatibility.patch

[UNO-578] Update CD to 7.4

---

composer.json
composer.lock
config/block.block.ochasearch.yml
config/core.extension.yml
config/ocha_search.settings.yml

UNO-579 ocha_search with GCSE ID and search block

---

composer.json
composer.lock

Update with most recent release https://github.com/UN-OCHA/common_design/releases/tag/v7.4.1
Refs: CD-254

Update base theme with user menu improvements

---

local/docker-compose.yml
tests/docker-compose.yml

Follow up to also use our images for the local stack and fix the entrypoint for the memache container.

fix: use our memcache and mysql images

---

config/image.style.hero_wide.yml
config/responsive_image.styles.1x_story.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.breakpoints.yml
html/themes/custom/common_design_subtheme/components/cd-hero/cd-hero--front.html.twig
html/themes/custom/common_design_subtheme/components/cd-hero/cd-hero--response.html.twig
html/themes/custom/common_design_subtheme/components/cd-hero/cd-hero--style-one.css
html/themes/custom/common_design_subtheme/components/cd-hero/cd-hero--style-two.css
html/themes/custom/common_design_subtheme/components/cd-hero/cd-hero.css

https://humanitarian.atlassian.net/browse/UNO-589
This was mainly for demonstration purposes and the specifics will be revisited - heights and max-widths will be revised, and hard-coded image replaced with those on the node, and/or a hero paragraph type (does not yet exist)

UNO-589 Story with 3:2 aspect ratio

---

config/core.entity_view_display.media.image.card.yml
config/core.entity_view_display.node.basic.card.yml
config/core.entity_view_display.node.basic.default.yml
config/core.entity_view_display.node.basic.teaser.yml
config/core.entity_view_display.node.event.card.yml
config/core.entity_view_display.node.event.teaser.yml
config/core.entity_view_display.node.region.card.yml
config/core.entity_view_display.node.region.teaser.yml
config/core.entity_view_display.node.response.card.yml
config/core.entity_view_display.node.response.teaser.yml
config/core.entity_view_display.node.story.card.yml
config/core.entity_view_display.node.story.teaser.yml
config/core.entity_view_mode.media.card.yml
config/image.style.hero_thumbnail.yml
config/views.view.media_centre.yml
config/views.view.responses.yml
config/views.view.stories.yml
html/themes/custom/common_design_subtheme/components/uno-card-list/uno-card-list.css
html/themes/custom/common_design_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-soft-footer.html.twig
html/themes/custom/common_design_subtheme/templates/content/media--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/media--image--hero.html.twig
html/themes/custom/common_design_subtheme/templates/content/media--image--story.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--story--card.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--story--full.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--content-list.html.twig

More Story content types, Views for Responses and Stories blocks and list pages.

UNO-589 Story nodes and Views

---

config/core.entity_view_display.node.region.title.yml

UNO-598 title view mode and display for region

---

html/themes/custom/common_design_subtheme/components/uno-mega-menu/uno-mega-menu.css
html/themes/custom/common_design_subtheme/css/styles.css

UNO-575 Mega menu columns and horizontal centering

---

composer.patches.json
patches/pathauto-php-82-compatibility.patch

Prevent deprecation warning in PHP 8.2.

chore: add PHP 8.2 compatibility patch for pathauto

---

composer.json
composer.lock

Last follow-up PR to #74 - remove menu block in favour of system menu
Refs: UNO-612

UNO-612 Remove menu block module

---

html/modules/custom/unocha_reliefweb/src/Services/ReliefWebApiClient.php

Refs: RW-759
Port of the the fix for RW from https://github.com/UN-OCHA/rwint9-site/pull/591 as the API client service was copied form RW.

fix: api filter optimization for ranges

---

config/unocha_reliefweb.settings.yml
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--reliefweb-document.html.twig

chore: remove hardcoded content in RW document paragraph template

---

config/core.extension.yml

chore: disable double field module ahead of removing
Refs: UNO-618

UNO-618 Remove double field module part 1

---

composer.json
composer.lock

Composer remove drupal/double_field
Refs: UNO-618

UNO-618 Remove double field module part 2

---

html/modules/custom/unocha_figures/src/Plugin/Field/FieldType/KeyFigure.php

fix: allow 0 as figure value

---

composer.json
composer.lock

UNO-628 Composer remove menu_position module

---

config/core.entity_form_display.media.image.media_library.yml
config/core.entity_form_display.paragraph.text_and_image.default.yml
config/core.entity_view_display.node.story.full.yml
config/views.view.stories.yml
html/modules/custom/unocha_reliefweb/templates/unocha-reliefweb-river.html.twig
html/modules/custom/unocha_reliefweb/unocha_reliefweb.module
html/themes/custom/common_design_claro/css/styles.css
html/themes/custom/common_design_subtheme/components/cd-caption/cd-caption.css
html/themes/custom/common_design_subtheme/components/cd-page-title/cd-page-title.css
html/themes/custom/common_design_subtheme/components/cd/cd.css
html/themes/custom/common_design_subtheme/components/uno-cta/uno-cta.css
html/themes/custom/common_design_subtheme/components/uno-layout/uno-layout.css
html/themes/custom/common_design_subtheme/components/uno-mega-menu/uno-mega-menu.css
html/themes/custom/common_design_subtheme/components/uno-nav/uno-nav.css
html/themes/custom/common_design_subtheme/components/uno-river/uno-river.css
html/themes/custom/common_design_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/templates/fields/field--node--field-custom-content.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--events.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--responses.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--video.html.twig
html/themes/custom/common_design_subtheme/templates/views/views-view--regions--regions.html.twig
html/themes/custom/common_design_subtheme/templates/views/views-view--responses--active-responses-menu.html.twig
html/themes/custom/common_design_subtheme/templates/views/views-view--responses--regional-responses.html.twig

UNO-575 alignment, vertical rhythm, Content Editor form styles, general style improvements
Some config to reorder paragraph and node field displays
UNO-630 Tabs for Latest news and stories View
UNO-624 caption and credits field display

UNO-575 More styles

---

config/field.field.node.event.field_region.yml
config/field.field.node.event.field_response.yml
config/field.field.node.response.field_region.yml
config/field.field.node.story.field_region.yml
config/field.field.node.story.field_response.yml
config/system.menu.main.yml

UNO-587 Improve admin help text
UNO-623 Entity reference field node order

UNO-587 UNO-623 admin help text and entity reference field node order

---

config/field.field.media.image.field_media_image.yml

feat: enable webp format for image media type
Refs: UNO-594

UNO-594 webp format for image media type

---

html/modules/custom/unocha_figures/src/Services/OchaKeyFiguresApiClient.php

[UNO-640] Fix issue with archived results from OCHA key figures

---

html/modules/custom/unocha_reliefweb/src/Plugin/Field/FieldFormatter/ReliefWebRiver.php

[UNO-605] Remove default title for RW rivers

---

html/themes/custom/common_design_subtheme/components/cd-banner/cd-banner.css
html/themes/custom/common_design_subtheme/components/cd-caption/cd-caption.css
html/themes/custom/common_design_subtheme/components/cd-card/cd-card.css
html/themes/custom/common_design_subtheme/components/cd-hero/cd-hero--style-three.css
html/themes/custom/common_design_subtheme/components/cd-hero/cd-hero.css
html/themes/custom/common_design_subtheme/components/cd-language-switcher/cd-language-switcher.css
html/themes/custom/common_design_subtheme/components/cd-social-links/cd-social-links.css
html/themes/custom/common_design_subtheme/components/cd-teaser/cd-teaser.css
html/themes/custom/common_design_subtheme/components/cd/cd.css
html/themes/custom/common_design_subtheme/components/rw-river/rw-river-article.css
html/themes/custom/common_design_subtheme/components/uno-breadcrumb/uno-breadcrumb.css
html/themes/custom/common_design_subtheme/components/uno-card-list/uno-card-list.css
html/themes/custom/common_design_subtheme/components/uno-figures/uno-figures.css
html/themes/custom/common_design_subtheme/components/uno-gho/uno-gho.css
html/themes/custom/common_design_subtheme/components/uno-layout/uno-layout.css
html/themes/custom/common_design_subtheme/components/uno-mega-menu/uno-mega-menu.css
html/themes/custom/common_design_subtheme/components/uno-nav/uno-nav.css
html/themes/custom/common_design_subtheme/components/uno-river/uno-river.css
html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css
html/themes/custom/common_design_subtheme/components/uno-tabs/uno-tabs.css
html/themes/custom/common_design_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/templates/content/node--region--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--response--full.html.twig

Styling across viewport widths

UNO-575 Responsive

---

config/core.entity_form_display.paragraph.subscribe.default.yml
config/core.entity_view_display.paragraph.subscribe.default.yml
config/field.field.paragraph.subscribe.field_text.yml
config/field.field.paragraph.subscribe.field_url.yml
html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--subscribe.html.twig

UNO-642 Subscribe

---

html/themes/custom/common_design_subtheme/components/cd-caption/cd-caption.css
html/themes/custom/common_design_subtheme/components/cd-tabs/cd-tabs.css
html/themes/custom/common_design_subtheme/components/cd-teaser/cd-teaser.css
html/themes/custom/common_design_subtheme/components/cd/cd.css
html/themes/custom/common_design_subtheme/components/uno-card-list/uno-card-list.css
html/themes/custom/common_design_subtheme/components/uno-donors/uno-donors.css
html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css
html/themes/custom/common_design_subtheme/css/styles.css

UNO-575 Linting

---

.github/workflows/run-tests.yml
README.md

Refs: OPS-9006
Just bringing the tests into line with those of the other repos - the change allows running them locally with https://github.com/nektos/act

chore: allow testing locally

---

docker/etc/nginx/custom/03_mapbox.conf

fix: SSL connection to mapbox

---

config/core.entity_form_display.paragraph.donors.default.yml
config/core.entity_view_display.paragraph.donors.default.yml
config/core.entity_view_display.paragraph.donors.preview.yml
config/field.field.paragraph.donors.field_figures_footnote.yml
config/field.field.paragraph.donors.field_url.yml
html/themes/custom/common_design_subtheme/components/uno-donors/uno-donors.css
html/themes/custom/common_design_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--donors.html.twig

Refs: UNO-663
This adds a footnote and source link field to the donors paragraph type.
Note: no styling for those fields.

[UNO-663] Donors footnote/link

---

composer.lock

[UNO-658] Update ocha key figures module

---

composer.patches.json
patches/ocha_key_figures-2.0.9-fixes.patch

Refs: UNO-658
@left23 Just a note that the patch in this PR should be removed once the ocha_key_figures is fixed upstream (https://github.com/UN-OCHA/ocha_key_figures/pull/6 and https://github.com/UN-OCHA/ocha_key_figures/pull/7).

[UNO-658] Add patch for ocha_key_figures module

---

html/themes/custom/common_design_subtheme/templates/content/node--basic--card.html.twig

And make region cards consistent
Refs: UNO-672

UNO-672 Card markup for basic page

---

html/modules/custom/unocha_menus/unocha_menus.module

Refs: UNO-667
Fix for the issue described in UNO-667.

[UNO-667] Fix wrong variable name

---

html/themes/custom/common_design_subtheme/components/cd-button/cd-button.css
html/themes/custom/common_design_subtheme/components/cd/cd.css
html/themes/custom/common_design_subtheme/components/uno-response-map/uno-response-map.css
html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css
html/themes/custom/common_design_subtheme/css/brand.css
html/themes/custom/common_design_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-footer.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--basic--card.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--card.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--event--card.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--region--card.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--response--card.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--response--map.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--story--card.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--response-map.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--responses.html.twig
html/themes/custom/common_design_subtheme/templates/uno/subscribe.html.twig

UNO-681 Design feedback

---

config/field.field.paragraph.subscribe.field_title.yml

chore: make title optional for subscribe paragraph type

---

html/themes/custom/common_design_subtheme/components/uno-donors/uno-donors.css
html/themes/custom/common_design_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-top-donors.html.twig

UNO-662 OCT Top Donors styles

---

config/views.view.stories.yml
html/themes/custom/common_design_subtheme/components/cd-tabs/cd-tabs.css

1. Remove Story type filter, no longer relevant since there are only 2 types and we have them in separate views.
2. Rename Views blocks to suit content
3. Adjust styles for primary-tabs

UNO-687 Stories View

---

html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--donors.html.twig

chore: change wording
Refs: UNO-570

UNO-570 Wording for OCT fineprint

---

config/system.site.yml

chore: set homepage to node ID of content on preview site
Refs: UNO-691

UNO-691 Set homepage to match preview site Node ID

---

composer.lock

[UNO-637] Update ocha_key_figures module to fix currency symbol issue

---

html/modules/custom/unocha_donors/src/Plugin/Field/FieldFormatter/Donors.php

[UNO-698] Fix display of regional office donors

---

html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--donors.html.twig

[UNO-694] Fix donor type in donors template

---

docker/etc/nginx/apps/drupal/drupal.conf

fix: css aggregation for Drupal 10.1+

---

docker/etc/nginx/apps/drupal/drupal.conf

fix: css/js aggregation for Drupal 10.1

---

docker/etc/nginx/apps/drupal/drupal.conf

fix: css/js aggregation for Drupal 10+ - attempt 3

---

config/views.view.stories.yml

UNO-701 Set story term for filter

---

config/core.entity_form_display.node.leader.default.yml

chore: reduce width of name and title fields for leader to prevent width issue
Refs: UNO-720

UNO-720 Widths of text fields for Leadership content type

---

config/field.field.node.leader.body.yml

chore: unset simple text editor so body field uses CKEditor as default
Refs: UNO-721

UNO-721 CKEditor for Leader textarea

---

config/core.entity_view_display.media.image.event.yml
config/core.entity_view_display.media.image.hero.yml
config/core.entity_view_display.media.image.story.yml
config/core.entity_view_display.media.video.default.yml
config/core.entity_view_display.media.video.gallery.yml
config/core.entity_view_display.node.leader.default.yml
config/core.entity_view_display.node.leader.teaser.yml
config/core.entity_view_display.node.leader.title.yml
config/core.entity_view_display.paragraph.reliefweb_river.cards.yml
config/core.entity_view_display.paragraph.reliefweb_river.teasers.yml
config/core.entity_view_display.paragraph.reliefweb_river_curated.default_paginated.yml
config/responsive_image.styles.1x_event.yml
config/responsive_image.styles.1x_hero_wide.yml
config/responsive_image.styles.1x_story.yml
config/responsive_image.styles.full_width.yml
config/responsive_image.styles.full_width_cropped.yml
config/responsive_image.styles.hero_image.yml
config/responsive_image.styles.portrait.yml
config/responsive_image.styles.story.yml
config/views.view.content.yml
config/views.view.files.yml
config/views.view.glossary.yml
config/views.view.media.yml
config/views.view.media_library.yml

chore: db from Prod and export config as there are some persistent config changes
Refs: OPS-9446

OPS-9446 Prod config export

---

html/themes/custom/common_design_subtheme/components/uno-leader/uno-leader.css
html/themes/custom/common_design_subtheme/templates/content/node--leader--teaser.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--leader--title.html.twig

chore: wrap image in div and adjust selectors so grid layout applies
Refs: UNO-575

UNO-575 Leadership layout

---

composer.json
composer.lock
config/config_split.config_split.config_dev.yml
config_dev/stage_file_proxy.settings.yml

OPS-9446 stage file proxy enable for dev using config split

---

config/system.site.yml

chore: set custom 404 to node id
Refs: UNO-693

UNO-693 Set 404 page

---

config/core.entity_view_display.media.image.card.yml
config/core.entity_view_display.media.image.event.yml
config/core.entity_view_display.media.image.gallery.yml
config/core.entity_view_display.media.image.hero.yml
config/core.entity_view_display.media.image.original_resized.yml
config/core.entity_view_display.media.image.story.yml
html/themes/custom/common_design_subtheme/templates/modules/ocha_search/ocha-search-block.html.twig

1. Override ocha_search template to replace aria-labelledby which is missing an ID, with aria-label
2. Change Media image label on custom view modes from visually-hidden to hidden
Refs: UNO-638

UNO-638 Accessibility improvements

---

html/themes/custom/common_design_subtheme/templates/uno/subscribe.html.twig

chore: change subscribe url so it works
Refs: UNO-575

UNO-575 Fix global subscribe form

---

composer.json
composer.lock

This is the module set that works for CD, so fingers crossed.
Refs: OPS-9482

feat: Add Azure AD (b2c) login.

---

html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--fts-top-sectors.html.twig

[UNO-738] Change title of top sectors

---

PATCHES/stage_file_proxy_3372105.patch
composer.patches.json

fix: Patch stage_file_proxy so it honours its settings.

---

config_dev/stage_file_proxy.settings.yml

chore: exclude css and js from the files retrieved by stage_file_proxy

---

config/user.role.editor.yml

fix: permission for editor to access page to edit terms

---

config/system.performance.yml
config/user.settings.yml

* Outright disable new user regs.
* Bump the content/render cache time.
Refs: OPS-8911

chore: A few go-live tweaks.

---

html/themes/custom/common_design_subtheme/components/cd-social-links/cd-social-links.html.twig

chore: add sitename to email share, fix twitter
Refs: UNO-734

UNO-734 Email and twitter share

---

config/user.role.editor.yml

chore: editors to add redirects
Refs: UNO-750

UNO-750 Editors to add redirects

---

config/user.role.editor.yml

Refs: UNO-749, UNO-750
Allow editors to modify the menus and access the menu settings on the node pages.

[UNO-750] Allow editors to modify the menus

---

config/core.entity_form_display.paragraph.node.default.yml
config/core.entity_view_display.node.story.teaser.yml
config/core.entity_view_display.paragraph.node.default.yml
config/field.field.paragraph.node.paragraph_view_mode.yml
config/metatag.metatag_defaults.front.yml
config/paragraphs.paragraphs_type.node.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/cd/cd-print.css
html/themes/custom/common_design_subtheme/components/cd/cd.css
html/themes/custom/common_design_subtheme/components/uno-response-map/uno-response-map.css
html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css

1. CSS validation issues
2. Media Centre menu item alignment
3. Print stylesheet
4. Remove default img from Metatag config
5. Improve Node paragraph type display for Cards and Teasers

UNO-575 Styles QA

---

html/themes/custom/common_design_subtheme/templates/layout/page--demo.html.twig

Prep for demo pages to display paragraphs and for VRT baseline.
Refs: UNO-762

UNO-762 Demo page template override

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/uno-pager/README.md
html/themes/custom/common_design_subtheme/components/uno-pager/uno-pager.css
html/themes/custom/common_design_subtheme/components/uno-views/uno-views.css

chore: uno-pager component, define library and set as dependency for views and rivers
Refs: UNO-678

UNO-678 Fix pager vertical rhythm on RW Rivers

---

PATCHES/core-ckeditor5-dialog-fix-3351600.patch
composer.patches.json

Refs: UNO-761
Just applying patch from https://www.drupal.org/project/drupal/issues/3351600 as this issue, while occasional, is annoying when it happens.

[UNO-761] Fix occasional issue with ckeditor in some browsers

---

docker/etc/nginx/custom/01_attachment_redirections.conf

chore: Handle rate limiting and internal errors differently, so the logs reflect that.

---

composer.json
composer.lock
config/config_split.config_split.config_dev.yml
config/core.extension.yml
config/environment_indicator.settings.yml
config/environment_indicator.switcher.dev.yml
config/environment_indicator.switcher.feature.yml
config/environment_indicator.switcher.prod.yml
config/environment_indicator.switcher.stage.yml
config_dev/environment_indicator.indicator.yml
config_dev/environment_indicator.switcher.local.yml

chore: add environment indicator module and config

---

config/config_split.config_split.config_dev.yml
config/environment_indicator.switcher.feature.yml

[OPS-8939] Fix environment indicator config

---

html/themes/custom/common_design_subtheme/translations/README.md
html/themes/custom/common_design_subtheme/translations/ar-common-design.po
html/themes/custom/common_design_subtheme/translations/es-common-design.po
html/themes/custom/common_design_subtheme/translations/fr-common-design.po

Translation strings from twig files in sub theme to .po files that came from base theme.
Custom strings for UNO starts at lines 58
Refs: UNO-772

UNO-772 Translation strings in .po files

---

composer.lock

chore: update ocha_key_figures module

---

local/README.md
local/install.sh
local/shared/settings/settings.site.php.example

Porting changes from https://github.com/UN-OCHA/rwint9-site/pull/647.

chore: update local stack

---

html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-top-donors.html.twig
html/themes/custom/common_design_subtheme/translations/ar-common-design.po
html/themes/custom/common_design_subtheme/translations/es-common-design.po
html/themes/custom/common_design_subtheme/translations/fr-common-design.po

Short-term alternative to https://github.com/UN-OCHA/unocha-site/pull/339
1. Checkout branch, clear cache
2. Visit https://unocha-local.test/our-funding and take note of the new title and text above the list of Donors.

UNO-780 Update hard-coded text

---

html/themes/custom/common_design_subtheme/components/uno-node/uno-node.css

Paragraph title field width restricted and centered horizontally
Refs: UNO-781

UNO-781 Paragraph title field width restricted and centered horizontally

---

local/docker-compose.yml

[RW-807] Change port for mailpit local service to work with caddy

---

html/themes/custom/common_design_subtheme/templates/uno/subscribe--global.html.twig

As a follow-up to https://github.com/UN-OCHA/unocha-site/pull/355/files, I ran Check1st again and it caught more issues with Mailchimp form that I missed in the previous PR.

UNO-784 accessibility

---

config/samlauth.authentication.yml

* Maintain the additional saml logs, so they go to ELK.
* Maintain the mail sync.
* Maintain the list of roles that is allowed to be linked.

fix: Commit the config changes that fixed the thing.

---

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module

fix: caching of story nodes

---

config/user.role.editor.yml

[UNO-794] Allow editors to edit OCHA presences

---

local/.env.example
local/README.md
local/docker-compose.yml
local/shared/settings/settings.local.php
local/shared/settings/settings.memcache.php

Refs: local-stack
Default DB username changed to remove the hyphen as that sometimes causes problems.
Changes in memcache settings come from RW.

chore: update local stack for consistency

---

config/editor.editor.ckeditor.yml
config/filter.format.ckeditor.yml

I also removed the left alignment icon option since it is the only one left and thus redundant.
Refs: UNO-814

UNO-814 Remove center alignment 

---

html/themes/custom/common_design_subtheme/components/cd/cd-header/cd-logo.css
html/themes/custom/common_design_subtheme/css/brand.css

with slight width reduction for best display.
Expected results:
Refs: UNO-815

UNO-815 adjust rules for desktop logo display on mobile

---

composer.json
composer.lock
config/core.entity_view_display.node.event.card.yml
config/core.entity_view_display.node.event.default.yml
config/core.entity_view_display.node.event.full.yml
config/core.entity_view_display.node.event.teaser.yml
config/core.extension.yml
html/themes/custom/common_design_subtheme/templates/fields/field--node--field-event-date.html.twig

feat: Use un_date

---

composer.lock

feat: Human friendly tz

---

html/themes/custom/common_design_subtheme/components/uno-paragraphs/uno-paragraphs.css

chore: vertical rhythm for rw rivers following donors
Follow up to https://github.com/UN-OCHA/unocha-site/pull/430
Refs: UNO-817

UNO-817 Vertical rhythm for RW Rivers following Donors

---

html/modules/custom/unocha_demo_content/content/node/08c68493-5b78-4c0a-a64a-99504634f80e.yml
html/modules/custom/unocha_demo_content/content/node/0c036e0c-d618-4894-9579-5fe14f344d6f.yml
html/modules/custom/unocha_demo_content/content/node/0c5ef5ad-e9b4-4e39-9258-adcdf1b69c0d.yml
html/modules/custom/unocha_demo_content/content/node/4585130a-2761-4e6d-8417-61815d493ea7.yml
html/modules/custom/unocha_demo_content/content/node/4aad45f9-f669-426d-b0a6-a53db101a48f.yml
html/modules/custom/unocha_demo_content/content/node/6dfc9cf6-da4f-41d7-ac3d-ef0dd36fc067.yml
html/modules/custom/unocha_demo_content/content/node/7069599a-4d94-45ac-ab74-49ead251ab78.yml
html/modules/custom/unocha_demo_content/content/node/712a1465-4697-490b-9763-622030a1e1e8.yml
html/modules/custom/unocha_demo_content/content/node/a1d1af93-901e-4a92-947b-31fa1c07906b.yml
html/modules/custom/unocha_demo_content/content/node/d028c4e4-2680-4325-a587-0b7f39a72894.yml
html/modules/custom/unocha_demo_content/content/node/d99b5bcc-d6df-4f2b-9fad-489992c84354.yml
html/modules/custom/unocha_demo_content/content/node/eae29c09-a631-458f-868c-1ee3ded7fc13.yml
html/modules/custom/unocha_demo_content/content/node/eef67247-3ed2-4bf6-9237-66282ab70e4d.yml
html/modules/custom/unocha_demo_content/content/node/f4f6154c-02b5-4a94-8a3f-f300d9455c23.yml
html/modules/custom/unocha_demo_content/content/node/ff34642c-7718-4808-b175-a3fa849587dc.yml

- Response and Resource pages
- Demo pages with Layouts and RW Rivers

UNO-817 Update demo content

---

composer.json
composer.lock

chore: update base theme to fix main nav last item display on smaller viewports
See https://github.com/UN-OCHA/common_design/releases/tag/v9.3.2
Refs: UNO-822

UNO-822 Fix last main menu item display on smaller viewport

---

html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css
html/themes/custom/common_design_subtheme/css/brand.css

chore: add css custom property for un blue and use for footer logo
Refs: UNO-821

UNO-821 Update colour of OCHA logo in footer

---

docker/Dockerfile

To prevent this issue 
`buildx failed with: ERROR: failed to solve: process "/bin/sh -c cp -a docker/settings.php docker/services.yml docker/memcache.services.yml html/sites/default" did not complete successfully: exit code: 1`
Refs: OPS-10074

OPS-10074 Composer super user

---

html/themes/custom/common_design_subtheme/_tests/FooterMenu.test.js
html/themes/custom/common_design_subtheme/_tests/HeadingOne.test.js
html/themes/custom/common_design_subtheme/_tests/MainMenuDropdown.test.js
html/themes/custom/common_design_subtheme/_tests/MegaMenuDropdown.test.js
html/themes/custom/common_design_subtheme/_tests/MobileMenu.test.js
html/themes/custom/common_design_subtheme/_tests/OCHAServices.test.js
html/themes/custom/common_design_subtheme/_tests/SearchDropdown.test.js
html/themes/custom/common_design_subtheme/_tests/_DebugEnv.test.js

Refs: OPS-10121
Just to see what happens.

tests: add workaround for test failure

---

config/core.entity_form_display.paragraph.ocha_datawrapper.default.yml
config/core.entity_view_display.paragraph.ocha_datawrapper.default.yml
config/core.entity_view_display.paragraph.ocha_datawrapper.preview.yml
config/core.extension.yml
config/field.field.paragraph.ocha_datawrapper.field_embed_code.yml
config/field.field.paragraph.ocha_datawrapper.field_text.yml
config/field.field.paragraph.ocha_datawrapper.field_title.yml
config/field.field.paragraph.ocha_datawrapper.field_url.yml
config/field.storage.paragraph.field_embed_code.yml
config/paragraphs.paragraphs_type.ocha_datawrapper.yml
config/user.role.editor.yml
html/modules/custom/ocha_datawrapper/js/datawrapper-responsive-iframe.js
html/modules/custom/ocha_datawrapper/ocha_datawrapper.info.yml
html/modules/custom/ocha_datawrapper/ocha_datawrapper.libraries.yml
html/modules/custom/ocha_datawrapper/ocha_datawrapper.module
html/modules/custom/ocha_datawrapper/ocha_datawrapper.permissions.yml
html/modules/custom/ocha_datawrapper/src/Plugin/Field/FieldFormatter/OchaDatawrapperFormatter.php
html/modules/custom/ocha_datawrapper/src/Plugin/Field/FieldWidget/OchaDatawrapperWidget.php
html/modules/custom/ocha_datawrapper/templates/ocha-datawrapper-formatter.html.twig

Refs: #UNO-829
Can be tested with
```
<iframe title="Presidential Approval Ratings Since Kennedy" aria-label="Interactive line chart" id="datawrapper-chart-t4fiQ" src="https://datawrapper.dwcdn.net/t4fiQ/3/" scrolling="no" frameborder="0" style="border: none;" width="600" height="578"></iframe>
```

feat: Add datawrapper

---

tests/vrt/urls_anon.txt

chore: reduce list by another two urls

---

config/csp.settings.yml

chore: enable minimum csp settings for beagle

---

composer.lock

chore: update version of monitoring module

---

config/core.extension.yml
config/seckit.settings.yml

chore: Alled media from ms

---

config/seckit.settings.yml

chore: include cbpfbp domain for csp

---

config/ocha_mediavalet.settings.yml
config/seckit.settings.yml

chore: CSP

---

html/themes/custom/common_design_subtheme/components/uno-section-tabs/uno-section-tabs.js
tests/docker-compose.yml

Refs: UNO-850
Still not quite sure why the current method returns an error - tabs[0] is defined, but this switch works similarly without the error.
Also, updating the test docker-compose.yml for consistency.

chore: fix js error

---

PATCHES/core_js_optimizer.patch
composer.patches.json

chore: fix js_optimizer error

---

config/core.entity_form_display.paragraph.ocha_powerbi.default.yml
config/core.entity_view_display.paragraph.ocha_powerbi.default.yml
config/core.entity_view_display.paragraph.ocha_powerbi.preview.yml
config/core.extension.yml
config/field.field.paragraph.ocha_powerbi.field_embed_link.yml
config/field.field.paragraph.ocha_powerbi.field_text.yml
config/field.field.paragraph.ocha_powerbi.field_title.yml
config/field.storage.paragraph.field_embed_link.yml
config/paragraphs.paragraphs_type.ocha_powerbi.yml
config/seckit.settings.yml
html/modules/custom/ocha_powerbi/README.md
html/modules/custom/ocha_powerbi/config/optional/core.entity_form_display.paragraph.ocha_powerbi.default.yml
html/modules/custom/ocha_powerbi/config/optional/core.entity_view_display.paragraph.ocha_powerbi.default.yml
html/modules/custom/ocha_powerbi/config/optional/core.entity_view_display.paragraph.ocha_powerbi.preview.yml
html/modules/custom/ocha_powerbi/config/optional/field.field.paragraph.ocha_powerbi.field_embed_link.yml
html/modules/custom/ocha_powerbi/config/optional/field.field.paragraph.ocha_powerbi.field_text.yml
html/modules/custom/ocha_powerbi/config/optional/field.field.paragraph.ocha_powerbi.field_title.yml
html/modules/custom/ocha_powerbi/config/optional/field.storage.paragraph.field_embed_link.yml
html/modules/custom/ocha_powerbi/ocha_powerbi.info.yml
html/modules/custom/ocha_powerbi/ocha_powerbi.module
html/modules/custom/ocha_powerbi/src/Plugin/Field/FieldFormatter/OchaPowerBiFormatter.php
html/modules/custom/ocha_powerbi/templates/ocha-powerbi-formatter.html.twig

feat: Embed PowerBi

---

html/modules/custom/ocha_mediavalet/src/Controller/MediaValetController.php

feat: Increase time-out for video proxy

---

html/modules/custom/unocha_donors/src/Plugin/Field/FieldFormatter/Donors.php

feat: Show message to editors

---

html/modules/custom/ocha_mediavalet/src/Api/MediaValetClient.php
html/modules/custom/ocha_mediavalet/src/Controller/MediaValetController.php

chore: Log calls to generate direct link

---

html/modules/custom/ocha_mediavalet/src/Api/MediaValetClient.php

chore: Update MediaValet payload

---

config/views.view.stories.yml

feat: Add filter for theme

---

config/core.entity_form_display.paragraph.stories.default.yml
config/core.entity_view_display.paragraph.stories.cards.yml
config/core.entity_view_display.paragraph.stories.cards_with_featured.yml
config/core.entity_view_display.paragraph.stories.default.yml
config/core.entity_view_display.paragraph.stories.teasers.yml
config/field.field.paragraph.stories.field_themes.yml
config/field.storage.paragraph.field_themes.yml
html/modules/custom/unocha_paragraphs/unocha_paragraphs.module

feat: Filter stories by theme

---

config/core.entity_form_display.node.leader.default.yml
config/core.entity_view_display.node.leader.default.yml
config/core.entity_view_display.node.leader.full.yml
config/core.entity_view_display.node.leader.title.yml
config/field.field.node.leader.field_custom_content.yml
html/themes/custom/common_design_subtheme/components/uno-leader/uno-leader.css

Refs: UNO-684
This adds the Custom Content (paragraph reference) field to the Leader content type and adjusts its display.

[UNO-684] Add custom content fields to leader content type

---

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module

Refs: fix
VRT picked up some errors with empty conditions. This check fixes the problem.

fix: avoid error

---

html/themes/custom/common_design_subtheme/components/cd/cd.css
html/themes/custom/common_design_subtheme/components/uno-card/uno-card.css
html/themes/custom/common_design_subtheme/components/uno-leader/uno-leader.css
html/themes/custom/common_design_subtheme/components/uno-node/uno-node.css
html/themes/custom/common_design_subtheme/components/uno-pager/uno-pager.css
html/themes/custom/common_design_subtheme/components/uno-paragraphs/uno-paragraphs.css
html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css
html/themes/custom/common_design_subtheme/components/uno-typography/uno-typography.css

feat: Reduce spacing from 6rem to 3rem

---

config/imagemagick.settings.yml

chore: specify imagemagick version

---

html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-social-menu.html.twig

feat: Social link in new tab

---

composer.json
composer.lock

chore: remove config_filter module

---

config/core.entity_form_display.node.basic.default.yml
config/core.extension.yml

chore: remove unused allowed_formats modules

---

config_dev/stage_file_proxy.settings.yml

fix: avoide stage_file_proxy error as in #3457368

---

local/shared/settings/settings.memcache.php

Refs: OPS-11411
As advised on https://github.com/UN-OCHA/gms-site/pull/544

updates: local memcache settings

---

html/modules/custom/unocha_donors/src/Plugin/Field/FieldFormatter/Donors.php

bug: wrong order of parameters

---

html/modules/custom/unocha_paragraphs/src/Element/MiniPager.php
html/modules/custom/unocha_paragraphs/templates/mini-pager.html.twig
html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
html/themes/custom/common_design_subtheme/components/uno-card-list/uno-card-list.css
html/themes/custom/common_design_subtheme/components/uno-paragraphs/uno-paragraphs.css
html/themes/custom/common_design_subtheme/templates/navigation/mini-pager.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--list-by-tags.html.twig

feat: Add paging

---

config/core.entity_form_display.paragraph.list_by_tags.default.yml
config/core.entity_view_display.paragraph.list_by_tags.cards.yml
config/core.entity_view_display.paragraph.list_by_tags.default.yml
config/core.entity_view_display.paragraph.list_by_tags.preview.yml
config/core.entity_view_display.paragraph.list_by_tags.teasers.yml
config/field.field.paragraph.list_by_tags.field_use_pager.yml
config/field.storage.paragraph.field_use_pager.yml

feat: Add paging fields

---

html/modules/custom/unocha_reliefweb/src/Controller/ReliefWebDocumentController.php

fix: remove deprecated function

---

config/field.storage.paragraph.field_order_by.yml

bug: sort by created

---

config/seckit.settings.yml

chore: add csp exception for clarity

---

.github/workflows/composer-update-config.yml
.github/workflows/composer-update-scripts.yml
.github/workflows/composer-update.yml

chore: use the updates job with scripts

---

composer.lock
composer.patches.json

chore: update dev_mode module

---

docker/Dockerfile
docker/etc/nginx/custom/04_legacy_files.conf
docker/etc/nginx/nginx.conf
docker/etc/nginx/sites-enabled/03_drupal_legacy_map.conf

feat: Redirect legacy DMS URLs.

---

PATCHES/imageapi_optimize_webp-imagemagick-toolkit.patch

chore: update patch to avoid removed function

---

composer.lock
composer.patches.json

With a bit of help because we can drop a patch now.

Update all outdated drupal/* unocha/* drush/* packages.

---

.github/workflows/composer-update.yml

chore: Use the visible / editable maintainers var for PR assignment.

---

composer.json
composer.lock

And remove some explicit dev requirements, as they should be in core-dev anyway.
Refs: OPS-11611

chore: Update core by loosening dev depends.
