composer.json, composer.lock, config/core.entity_form_display.paragraph.stories.default.yml, config/core.entity_view_display.paragraph.stories.default.yml, config/core.extension.yml, config/field.field.paragraph.stories.field_limit.yml, config/field.field.paragraph.stories.field_title.yml, config/field.storage.paragraph.field_limit.yml, config/paragraphs.paragraphs_type.stories.yml, config/views.view.stories.yml, html/modules/custom/unocha_paragraphs/README.md, html/modules/custom/unocha_paragraphs/unocha_paragraphs.info.yml, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--stories.html.twig
Refs: UNO-598, UNO-630, UNO-631
This PR does the following:
**News and Stories view**
1. Adds the drupal/verf module to be able to use a dropdown for the region and response filters
2. Updates the filters with a OR condition for the country, response and region to better it the view all links (see below, point 4 of stories paragraph type)
Notes:
- The "Stories" paragraph type replaces the blocks of the "News and Stories" view and should be removed when we clean up things.
**Stories paragraph type**
1. Adds a "Stories" paragraph type with a "title" (defaults to "Latest News and Stories") and a limit field (defaults to 3)
2. Adds the `unocha_paragraphs` module with notably a preprocess hook for the "stories" paragraph type with the logic to get the stories to display based on the parent of …
=> [UNO-631] Stories paragraph type

config/core.entity_form_display.node.resource.default.yml, config/core.entity_form_display.paragraph.resources.default.yml, config/core.entity_view_display.node.resource.default.yml, config/core.entity_view_display.node.resource.full.yml, config/core.entity_view_display.node.resource.teaser.yml, config/core.entity_view_display.paragraph.resources.default.yml, config/field.field.node.resource.body.yml, config/field.field.node.resource.field_custom_content.yml, config/field.field.paragraph.resources.field_title.yml, config/language.content_settings.node.resource.yml, config/node.type.resource.yml, config/paragraphs.paragraphs_type.resources.yml, config/pathauto.pattern.resources.yml, config/views.view.content.yml, html/modules/custom/unocha_paragraphs/README.md, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--resources.html.twig
Refs: UNO-610
Note: this based of the "UNO-631-stories" from https://github.com/UN-OCHA/unocha-site/pull/98 because it extends the `unocha_paragraphs` module.
This PR adds a Resource content type to use for the response resource pages and a Resources paragraph type that displays the resources of a response.
This is handled by looking at the children of the reponse menu item. That means to add a resource to a response, editors have to select it as the parent menu when selecting the menu link item on the resource node form.
Note: another approach could be have a "response" entity reference field on the resource content type but the advantage of the menu approach is that we don't need to do anything for the breadcrumbs of the resource page as it's derived from the menu hierarchy.
See notes …
=> [UNO-610] Resources

config/core.extension.yml, html/modules/custom/unocha_breadcrumbs/README.md, html/modules/custom/unocha_breadcrumbs/src/Services/UnochaBreadcrumbBuilder.php, html/modules/custom/unocha_breadcrumbs/unocha_breadcrumbs.info.yml, html/modules/custom/unocha_breadcrumbs/unocha_breadcrumbs.services.yml, html/modules/custom/unocha_reliefweb/src/Controller/ReliefWebDocumentController.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebBreadcrumbBuilder.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebDocuments.php, html/modules/custom/unocha_reliefweb/unocha_reliefweb.services.yml
Refs: UNO-628
Note: this PR is against the `UNO-628-breadcrumbs` branch from https://github.com/UN-OCHA/unocha-site/pull/92
This PR adds `BreadcrumbBuilder` services to handle the breadcrumbs for the RW white labeled documents and the events and stories.
The parts of the breadcrumbs are hardcoded for simplicity and performance. The code is simple enough that it should be easy to adjust the breadcrumbs.
1. Checkout this branch, clear the cache and import the config
2. Visit a RW press release, check the breadcrumb
3. Visit a RW speech, check the breadcrumb
4. Visit a story, check the breadcrumb
5. Visit an event, check the breadcrumb
=> [UNO-628] Breadcrumbs for RW docs, events and stories

html/modules/custom/unocha_maps/components/response-map/response-map.js, html/modules/custom/unocha_maps/unocha_maps.module, html/themes/custom/common_design_subtheme/components/uno-response-map/uno-response-map.css, html/themes/custom/common_design_subtheme/templates/content/node--response--map.html.twig
Refs: UNO-627
Follow-up of https://github.com/UN-OCHA/unocha-site/pull/112 to sort responses by priority then name and better handle responses with overlapping countries (shown as "related responses" below the response currently displayed next to the map).
1. Create a response, tag it with a country already used by another response, select the same parent region, save
2. Check that when clicking the marker for the country from (1), the displayed response has a "related responses" list with the other response(s) tagged with the same country
3. Also check that the first "selected" response changes when checking "priority response" for one of them.
=> [UNO-627] Maps - related responses

config/core.entity_form_display.paragraph.reliefweb_river.default.yml, config/core.entity_view_display.paragraph.reliefweb_river.cards_paginated.yml, config/core.entity_view_display.paragraph.reliefweb_river.teasers_paginated.yml, config/core.entity_view_mode.paragraph.cards_paginated.yml, config/core.entity_view_mode.paragraph.teasers_paginated.yml, html/modules/custom/unocha_reliefweb/config/schema/unocha_reliefweb.schema.yml, html/modules/custom/unocha_reliefweb/src/Plugin/Field/FieldFormatter/ReliefWebRiver.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebDocuments.php, html/modules/custom/unocha_reliefweb/templates/unocha-reliefweb-river-results.html.twig
Refs: UNO-633
This adds an option of the RW river formatters to display a pager (and the results) for a river.
This also adds 2 new view modes, used for RW river paragraphs: Teasers (paginated) and Cards (paginated). When selecting such a view mode, the pager will be displayed for the river.
1. Edit the press releases page, edit the paragraph type, select "Teasers (paginated)" as view mode, save
2. Open the press releases page and check that the pager is displays at the bottom of the river and works and that the "Showing X-Y of Z" is shown a the top of the river.
=> [UNO-633] RW river pagination

html/modules/custom/unocha_canto/assets/canto/library.css, html/modules/custom/unocha_canto/assets/canto/library.html, html/modules/custom/unocha_canto/assets/canto/library.js
Refs: UNO-632
This adds pagination to the Canto library widget so it's possible to select older images.
1.  Checkout the branch, clear the cache
2. Edit a response for example, add a media, click select from Canto
3. Check that the pager appears at the below the images and click on some links to confirm the list is updated
=> [UNO-632] Add pagination to Canto library widget

config/paragraphs.paragraphs_type.reliefweb_river.yml, html/themes/custom/common_design_claro/templates/form/layout-paragraphs-builder-component-menu.html.twig
Refs: UNO-634
This sorts the paragraph types in the selector widget and also adds labels to distinguish layout paragraphs and content ones:
1. Checkout the branch, clear the cache and import the config
2. Edit a story for example, click the button to add a paragraph and verify that the list of paragraph types is ordered
=> [UNO-634] Order paragraph types in widget

config/core.entity_form_display.paragraph.subscribe.default.yml, config/core.entity_view_display.paragraph.subscribe.default.yml, config/field.field.paragraph.subscribe.field_title.yml, config/field.field.paragraph.subscribe.field_url.yml, config/field.storage.paragraph.field_url.yml, config/paragraphs.paragraphs_type.subscribe.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/uno-subscribe/README.md, html/themes/custom/common_design_subtheme/components/uno-subscribe/uno-subscribe.css, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--subscribe.html.twig, html/themes/custom/common_design_subtheme/templates/uno/subscribe.html.twig
Refs: UNO-642
This PR adds a `subscribe` paragraph type that accepts a URL (ex: mailchimp subscription URL) and a title (used as label for the input field and submit button label).
It uses the `uno/subscribe.html.twig` template and there is a new `uno-subscribe` component for the styling (currently not doing much there).
2. Edit a response for example and add a `subscribe` paragraph type
3. Save
4. Check that the `title` field is used for the button label and that the form redirects to URL of the mailing list entered in the URL field.
=> [UNO-642] Subscribe paragraph type

html/modules/custom/unocha_reliefweb/src/Controller/ReliefWebDocumentController.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebDocuments.php, html/themes/custom/common_design_subtheme/templates/layout/page--404.html.twig
Refs: UNO-643
This replaces the filter on the OCHA product field with a filter on the source field because some documents prior to 2016 do not have a OCHA product.
=> [UNO-643] RW OCHA documents

config/core.entity_view_display.node.leader.teaser.yml, config/core.entity_view_display.node.leader.title.yml, config/core.entity_view_display.node.response.full.yml, config/editor.editor.ckeditor.yml, config/filter.format.ckeditor.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/cd-social-links/cd-social-links.css, html/themes/custom/common_design_subtheme/components/cd/cd.css, html/themes/custom/common_design_subtheme/components/uno-card-list/uno-card-list.css, html/themes/custom/common_design_subtheme/components/uno-cta/uno-cta.css, html/themes/custom/common_design_subtheme/components/uno-layout/uno-layout.css, html/themes/custom/common_design_subtheme/components/uno-leader/uno-leader.css, html/themes/custom/common_design_subtheme/components/uno-nav/uno-nav.css, html/themes/custom/common_design_subtheme/components/uno-text-image/uno-text-image.css, html/themes/custom/common_design_subtheme/css/styles.css, html/themes/custom/common_design_subtheme/templates/content/node--leader--teaser.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--leader--title.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--text-and-image.html.twig
UNO-638 Styles for Leadership page - paragraph type and full node, in a 2 column layout for USG/ASG
UNO-575 More responsive related items and refactoring based on VRT screenshots
Import config for 
1. adding alignment (left, center) to CK Editor WYSIWYG
2. Rearranging Leader field order in display
3. Displaying Response region on Full for label in template
=> UNO-638 UNO-575 Leader and other styles

config/core.entity_form_display.paragraph.donors.default.yml, config/core.entity_view_display.paragraph.donors.default.yml, config/core.entity_view_display.paragraph.donors.preview.yml, config/core.extension.yml, config/field.field.paragraph.donors.field_countries.yml, config/field.field.paragraph.donors.field_donor_type.yml, config/field.storage.paragraph.field_countries.yml, config/field.storage.paragraph.field_donor_type.yml, config/paragraphs.paragraphs_type.donors.yml, html/modules/custom/unocha_donors/README.md, html/modules/custom/unocha_donors/templates/unocha-donors-list.html.twig, html/modules/custom/unocha_donors/unocha_donors.info.yml, html/modules/custom/unocha_donors/unocha_donors.module, html/modules/custom/unocha_utility/src/TwigExtension.php, html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/uno-donors/README.md, html/themes/custom/common_design_subtheme/components/uno-donors/uno-donors.css, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--cbpf-top-donors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--fts-top-donors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--fts-top-sectors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-top-earmarked.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-unearmarked-donors.html.twig
Refs: UNO-635
This PR adds a `donors` paragraph type and the `unocha_donors` module with the logic to get the donors data from the OCHA API.
1. Add a "Donors" paragraph type
2. Select the data source (ex: FTS)
3. Select the country or countries for which to get the data
There are templates in `common_design_subtheme/templates/modules/unocha_donors` for the 5 types of donors/sectors data and a `uno-donors` component but there almost zero styling currently. 
1. Checkout the branch, clear the cache and import the config
2. Follow the "wokflow" steps
=> [UNO-635] Donors paragraph type

config/core.entity_form_display.node.basic.default.yml, config/core.entity_view_display.node.basic.card.yml, config/core.entity_view_display.node.basic.default.yml, config/core.entity_view_display.node.basic.full.yml, config/core.entity_view_display.node.basic.teaser.yml, config/field.field.node.basic.field_children_menu.yml, config/field.storage.node.field_children_menu.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.theme
Refs: UNO-648
This adds a "children menu" field to basic pages that, when checked, displays a menu of the page and its children as tabs (menu local tasks).
The logic is in a preprocess in the common_design_subtheme and the templates can be overridden:
1. `menu-local-tasks--children-menu.html.twig`
2. `menu-local-task--children-menu.html.twig`
For example (2) could be used to check the link "title" and the "active" state and alter the title:
```
{% if element['#link'].title == 'Publications'|t and element['#active'] is not empty %}
{% set link = link|merge({'#title': 'Latest'|t}) %}
{% endif %}
<li{{ attributes }}>{{ link }}</li>
```
The menu (field_children_menu) is currently displayed below the title and hero image if there is one. This could be altered either in the basic page's display …
=> [UNO-648] Menu tabs

html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-earmarked-donors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-unearmarked-donors.html.twig
Refs: UNO-635
Fixes for the OCT donors:
1. show amount for OCT earmarked donors
2. closing tag for the OCT unearmarked list
=> [UNO-635] Donors fixes

html/modules/custom/unocha_maps/unocha_maps.module, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-652
This adds access checks for the maps, resources and stories used in the corresponding paragraph types.
1. Checkout the branch, clear the cache
2. Unpublish a response that appears in a region's map, check that it appears on the map when logged in as an editor but is not present when viewing the map as an anonymous user
3. Unpublish a story that appears in a "latest updates" section of a region, check that it doesn't appear anymore in that section (whether logged in or not)
4. Unpublish a resource that appears in a response's resources section, check that it's visible in the resources section as en editor but not when viewing it as anonymous
Note: regarding (3) above and stories. The behavior is a bit different from the maps and resources where unpublished nodes still appear …
=> [UNO-652] Check access to nodes

config/user.settings.yml
This sets is to administrators approval required, which is probably still not what we want, but better than nothing.
Refs: OPS-8911
=> feat: Disable open user registrations.

html/themes/custom/common_design_subtheme/common_design_subtheme.theme
Refs: UNO-648
This PR ensures a menu is not displayed as mega menu when its expanded property is unchecked.
Make sure that menus that should show their children have the `Show as expanded` property checked. Currently that means the menu items for the region pages (it seems to be already the case on dev, but to also do when populating the preview site).
**Before checking out the branch**
1. Confirm, the "latest" menu appears as a mega menu on your local when visiting `/publications`
2. If not, import the latest dev DB backup
**After checking out the branch**
1. Checkout the branch and clear the cache.
2. Check that the "latest" menu is not a mega menu anymore when visiting `/publications` and its children pages
3. Check some other pages like a response and confirm that "latest" is not a …
=> [UNO-648] Fix publications menu

composer.json, composer.lock, config/core.entity_form_display.paragraph.cbpf.default.yml, config/core.entity_view_display.paragraph.cbpf.default.yml, config/core.entity_view_display.paragraph.cbpf.preview.yml, config/core.extension.yml, config/field.field.paragraph.cbpf.field_cbpf_attributes.yml, config/field.field.paragraph.cbpf.field_cbpf_id.yml, config/field.field.paragraph.cbpf.field_height.yml, config/field.field.paragraph.cbpf.field_text.yml, config/field.field.paragraph.cbpf.field_title.yml, config/field.field.paragraph.cbpf.field_url.yml, config/field.field.paragraph.cbpf.field_width.yml, config/field.storage.paragraph.field_cbpf_attributes.yml, config/field.storage.paragraph.field_cbpf_id.yml, config/field.storage.paragraph.field_height.yml, config/field.storage.paragraph.field_width.yml, config/paragraphs.paragraphs_type.cbpf.yml, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--cbpf.html.twig
Refs: UNO-653
This adds a "CBPF" paragraph type to display a visualisation from https://github.com/CBPFGMS/cbpfgms.github.io/.
The paragraph requires a visualisation ID from the link above and dimensions (to determine the aspect ratio).
After that the visualisation is displayed via an iframe.
Make a backup of the DB before testing because, this PR adds a new module and paragraph type so switching back to another branch without merging this PR will make Drupal complain when importing the config.
1. Checkout the branch
2. Run `composer install`, clear the cache and import the config
3. Edit/create a page (ex: basic page)
4. Add a CBPF paragraph, select an ID from https://github.com/CBPFGMS/cbpfgms.github.io/, for example the ID of the graph shown on …
=> [UNO-653] CBPF visualisations

html/modules/custom/unocha_breadcrumbs/src/Services/UnochaBreadcrumbBuilder.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebBreadcrumbBuilder.php
Refs: UNO-641
This adds a caching context on the URL for the custom breadcrumbs to avoid showing the wrong cached breadcrumbs on some pages.
**Before checking out the branch**
1. Check that all the `$settings['cache']['bins']['xxx'] = 'cache.backend.null';` are commented out in your local settings.php file(s)
2. Check that you get the issue mentioned in UNO-641, otherwise merge this PR and test on `dev`
**After checking out the branch**
1. Check the proper breadcrumbs appear after following the steps from UNO-641
=> [UNO-641] caching context for breadcrumbs

config/field.field.media.image.field_media_image.yml
Refs: UNO-651
Add description to media image field to indicate that files with 2 extensions should be renamed
=> [UNO-651] Media image field description

html/themes/custom/common_design_subtheme/components/cd-social-links/cd-social-links.css, html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css, html/themes/custom/common_design_subtheme/templates/modules/unocha_reliefweb/unocha-reliefweb-document.html.twig
Refs: UNO-675
This updates the RW document template to add the social share links.
1. Visit a whitelabeled RW document page, check that the social links appear and have the proper query parameters.
=> feat: add social share links to RW document pages

config/core.entity_form_display.paragraph.news_and_stories.default.yml, config/core.entity_view_display.paragraph.news_and_stories.default.yml, config/field.field.paragraph.news_and_stories.field_news_and_stories_list.yml, config/field.storage.paragraph.field_news_and_stories_list.yml, config/paragraphs.paragraphs_type.news_and_stories.yml, config/views.view.stories.yml, html/themes/custom/common_design_subtheme/templates/navigation/menu-local-task--children-menu.html.twig
Refs: UNO-670
This adds a "News and Stories" paragraph type with a views reference field defaulting to the "Stories" view.
It also changes the "Stories" view to use blocks instead of pages.
So, with that, it's possible to show the list of news and stories via a paragraph on a basic page and use the "children menu" feature to display tabs for the different "news" pages.
**Note:** To use the children menu feature, the "News", "Stories", "Press releases" and "Statements" need to be added as child pages of the "Latest news and stories" page.
**Note:** Because there is path alias pattern for basic pages, the path alias on the node form needs to be set manually (ex: `/latest/stories`.
2. Create the "Latest news and stories" page, add …
=> [UNO-670] Add news and stories paragraph type and change stories views

config/core.entity_form_display.node.response.default.yml, config/core.entity_view_display.node.response.card.yml, config/core.entity_view_display.node.response.default.yml, config/core.entity_view_display.node.response.full.yml, config/core.entity_view_display.node.response.map.yml, config/core.entity_view_display.node.response.teaser.yml, config/core.entity_view_display.node.response.title.yml, config/core.extension.yml, config/field.field.node.response.field_has_response.yml, config/field.field.node.response.field_office_type.yml, config/field.storage.node.field_has_response.yml, config/field.storage.node.field_office_type.yml, config/language.content_settings.taxonomy_term.office_type.yml, config/taxonomy.vocabulary.office_type.yml, html/modules/custom/unocha_maps/unocha_maps.module, html/modules/custom/unocha_menus/README.md, html/modules/custom/unocha_menus/unocha_menus.info.yml, html/modules/custom/unocha_menus/unocha_menus.module
Refs: UNO-667
This PR adds the "has response" and "office type" fields to the response content type. It also adds the "Office type" taxonomy vocabulary.
The "has response" field is used to flag a response as having an actual current response. Responses with that flag appear on the map on the homepage.
The "office type" is used as a filter for the regional maps where responses with **only** a liaison office don't appear on the map.
The PR also exposes the `expanded` and `enabled` properties of the menu link items on the node form. `Expanded` should notably selected for regions to show their children in the "where we work" mega menu. 
The `enabled` field is named "visible" in the form and is selected by default. When unchecked, the menu will not appear in the main navigation menu. This can …
=> [UNO-667] Add has response and office type fields and vocabulary

config/core.entity_form_display.paragraph.reliefweb_river.default.yml, config/core.entity_form_display.paragraph.reliefweb_river_curated.default.yml, config/core.entity_view_display.paragraph.reliefweb_river.cards.yml, config/core.entity_view_display.paragraph.reliefweb_river_curated.cards.yml, config/core.entity_view_display.paragraph.reliefweb_river_curated.default.yml, config/core.entity_view_display.paragraph.reliefweb_river_curated.default_paginated.yml, config/core.entity_view_display.paragraph.reliefweb_river_curated.teasers.yml, config/field.field.paragraph.reliefweb_river_curated.field_limit.yml, config/field.field.paragraph.reliefweb_river_curated.field_reliefweb_documents.yml, config/field.field.paragraph.reliefweb_river_curated.field_text.yml, config/field.field.paragraph.reliefweb_river_curated.field_title.yml, config/field.field.paragraph.reliefweb_river_curated.paragraph_view_mode.yml, config/field.storage.paragraph.field_reliefweb_documents.yml, config/paragraphs.paragraphs_type.reliefweb_river_curated.yml, html/modules/custom/unocha_reliefweb/config/schema/unocha_reliefweb.schema.yml, html/modules/custom/unocha_reliefweb/src/Plugin/Field/FieldFormatter/ReliefWebDocumentRiver.php, html/modules/custom/unocha_reliefweb/src/Plugin/Field/FieldFormatter/ReliefWebRiver.php, html/modules/custom/unocha_reliefweb/src/Plugin/Validation/Constraint/ReliefWebDocumentUrlConstraint.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebDocuments.php, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--reliefweb-river-curated.html.twig
Refs: UNO-668
This PR adds a new "ReliefWeb - River - Curated" paragraph type which allows to create a list of RW documents by providing individual document URLs.
It uses the same template as the the normal RW river paragraph type so no styling changes. 
The river also uses the same ordering by publication date than automated rivers so the order of the RW document URLs in the form doesn't matter.
The PR includes a few fixes for the rivers notably for the pagination.
1. Checkout, clear the cache, import the config
2. Edit a page (ex: press releases page)
3. Add a "ReliefWeb - River - Curated" paragraph type, add some OCHA documents on https://reliefweb.int, select default (paginated)  as view mode to be able to confirm the list contains all the selected documents.
4. Save and check that …
=> [UNO-668] Curated RW river

config/field.field.paragraph.events.field_events.yml, config/views.view.events.yml, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module, html/themes/custom/common_design_subtheme/css/styles.css
Refs: UNO-684
This adds a contextual filter for the "upcoming events" view block that can be used to filter the list of events based on the event type (default  = no filter = all events).
This goes with some form manipulations for the events field of the events paragraph type to show a dropdown to select the event type when "upcoming events" is selected.
It also exposes pagination settings so that editors can select whether to show all events, all events with pagination or a limited number of events.
**Note**
It's possible to add other blocks to the "events" view and enable the selection of the event type by adding the contextual filter as the "upcoming events" block's one.
1. Checkout, clear the cache and import the config
2. Create some events
3. Edit a page and add an "events" …
=> [UNO-684] Events

config/core.date_format.unocha.yml, html/themes/custom/common_design_subtheme/templates/fields/field--node--field-event-date.html.twig
Refs: UNO-649
This changes the display of the date field for the event nodes according to the discussion in UNO-649. (This makes the logic much simpler.)
2. Create or edit an event node.
3. Set different dates, save and check the display is correct, notably the timezone
4. Set the same day for the start and end date but with different time, check that both dates are displayed
5. Set the same day and same time, check that only one date is displayed with the "Date:" label
=> [UNO-649] Date field display for events paragraphs

composer.lock
Refs: OHA-58
Update ocha_key_figures module to fix issue with current year option for regional office donors.
=> [OHA-58] Update ocha_key_figures module

html/themes/custom/common_design_subtheme/common_design_subtheme.theme
Refs: UNO-695
This uses the menu weight to order the tabs for example on the News and stories page. So order is the same as the order of the children menu links and can be adjusted in `/admin/structure/menu/manage/main` or by changing the weight in the children node forms.
=> [UNO-695] Order tabs by menu weight

config/field.field.paragraph.donors.field_country_donors.yml, config/field.field.paragraph.donors.field_presence_donors.yml
Refs: UNO-702
The config was missing the `top-sectors` in the allowed list of figures.
=> [UNO-702] Allow selection of top sectors

composer.patches.json, config/core.entity_form_display.paragraph.figures.default.yml, config/core.entity_view_display.paragraph.figures.default.yml, config/core.entity_view_display.paragraph.figures.figures.yml, config/core.entity_view_display.paragraph.figures.figures_compact_long.yml, config/core.entity_view_display.paragraph.figures.figures_compact_short.yml, config/field.field.paragraph.figures.field_figures.yml, config/field.field.paragraph.figures.field_presence_figures.yml, config/field.storage.paragraph.field_presence_figures.yml, patches/ocha_key_figures-ocha-presence-figures.patch
Refs: UNO-703
This PR adds a "Regional / country office figures" field to the `figures` paragraph type to be able to select ROAP funding figures from OCT for example.
There is a `patch for the `ocha_key_figures` module that corresponds to this PR: https://github.com/UN-OCHA/ocha_key_figures/pull/13. Once it is merged and there is a new release please remove the patch and upgrade:
1. Remove `patches/ocha_key_figures-ocha-presence-figures.patch`
2. Remove the corresponding entry in `composer.patches.json`
3. Run `composer update unocha/ocha_key_figures`
4. Commit the change to `composer.json` and `composer.lock`
1. Checkout the branch, run `composer install` to patch the `ocha_key_figures` module, clear the cache and import the config
2. Edit a region for example, and use the `Regional / …
=> [UNO-703] Regional figures

html/themes/custom/common_design_subtheme/templates/modules/ocha_key_figures/ocha-key-figures-figure.html.twig
Refs: UNO-705
This shows the `%` unit after the figure label as per the other non percentage figures:
See https://github.com/UN-OCHA/unocha-site/pull/216 for an alternative.
=> [UNO-705] Show percentage unit

config/core.entity_form_display.node.story.default.yml, config/core.entity_view_display.node.story.campaign.yml, config/core.entity_view_display.node.story.card.yml, config/core.entity_view_display.node.story.default.yml, config/core.entity_view_display.node.story.full.yml, config/core.entity_view_display.node.story.teaser.yml, config/field.field.node.story.field_regions.yml, config/field.field.node.story.field_responses.yml, config/field.storage.node.field_regions.yml, config/field.storage.node.field_responses.yml, config/views.view.stories.yml, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-710
This adds 2 new fields: `field_regions` and `field_responses` on the story content type to replace the `field_region` and `field_response` which accepted only 1 value; and update the logic for the stories paragraph type and views to use those new fields.
The  `field_region` and `field_response` are hidden but not removed otherwise that may break the deployment on the preview site.
So before deploying, manually delete the **story** `field_region` and `field_response` on the preview site. They will be recreated as part of the deployment but that will ensure there is no leftover.
As a follow-up **after** the deployment of this branch, we'll have to create a PR that actually removes those fields for the **story** content type.
1. Checkout the branch, clear the cache, import the …
=> [UNO-710] Stories - multiple regions/responses

composer.lock, html/modules/custom/unocha_donors/src/Plugin/Field/FieldFormatter/Donors.php, html/modules/custom/unocha_utility/src/Helpers/NumberFormatter.php, html/themes/custom/common_design_subtheme/templates/modules/ocha_key_figures/ocha-key-figures-figure.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--cbpf-top-donors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--fts-top-donors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--fts-top-sectors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-earmarked-donors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-top-donors.html.twig, html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-unearmarked-donors.html.twig
Refs: UNO-708, UNO-716, UNO-717
This PR combines related fixes for the donors and figures:
1. Display figure values of `0` as `0` instead of `-`
2. Fix amount not being displayed for top sectors
3. Order donor figures similarly to the current www.unocha.org
1. Checkout the branch, run composer install, clear the cache
2. Go to the Ukraine page, check that the donors and sector show similar data as https://www.unocha.org/ukraine
3. Go to the Eritrea page, check that the "funding for OCHA Eritrea" show `0` instead of `-`
=> [UNO-708][UNO-716][UNO-717] Figures and donors

config/core.extension.yml, config/xmlsitemap.settings.node.basic.yml, config/xmlsitemap.settings.node.event.yml, config/xmlsitemap.settings.node.leader.yml, config/xmlsitemap.settings.node.media_collection.yml, config/xmlsitemap.settings.node.region.yml, config/xmlsitemap.settings.node.resource.yml, config/xmlsitemap.settings.node.response.yml, config/xmlsitemap.settings.node.story.yml, config/xmlsitemap.settings.yml, config/xmlsitemap.xmlsitemap.g3XYqcXbSKPVBDODwnT6pq7oqhCFkPryj4vVqrl_Kfc.yml, html/modules/custom/unocha_sitemap/README.md, html/modules/custom/unocha_sitemap/unocha_sitemap.info.yml, html/modules/custom/unocha_sitemap/unocha_sitemap.install, html/modules/custom/unocha_sitemap/unocha_sitemap.module
Refs: UNO-580
This PR configures the `xmlsitemap` module and add a hook implementation to also create links for the white labeled RW documents.
The `xmlsitemap` module doesn't store the  base url it uses for the links in `config` and doesn't use the site base URL... (see: https://www.drupal.org/project/xmlsitemap/issues/2832471). 
So after deployment, one needs to go to `/admin/config/search/xmlsitemap/settings` and under `advanced settings`, set the  "default base URL" to something appropriate for the site (ex: https://www.unocha.org for prod before launch).
1. Checkout the  branch, clear the cache, import the config
2. Run `drush sql-query "SHOW CREATE TABLE xmlsitemap"` and check that the `loc` field is a `varchar(2048)`
3. Set up the base URL as per the above "deployment" instructions …
=> [UNO-580] Sitemap

config/views.view.stories.yml
Refs: UNO-712
Change view config to show 12 items on the stories page to avoid blank before pager.
=> [UNO-712] Stories - number of items

html/themes/custom/common_design_subtheme/package-lock.json
Refs: OPS-8923
Runs `npm audit fix` for the subtheme.
This fixes https://github.com/UN-OCHA/unocha-site/security/dependabot/12 as the original word-wrap package looks abandoned.
=> chore: run npm audit fix

docker/etc/nginx/custom/04_ecosoc_files.conf, docker/etc/nginx/custom/04_legacy_files.conf
This is so that ECOSOC documents may remain available at their existing URL and ECOSOC will continue to like us. Additonally, there is a provision for a generic "legacy" subdir under files where other "migrated" documents from the Drupal 7 files may live.
Refs: OPS-9445
=> feat: Rewrite URLs for the old /sites/unocha/files path.

config/core.entity_view_display.media.image.original_resized.yml, config/core.entity_view_display.paragraph.image.default.yml, config/core.entity_view_display.paragraph.text_and_image.default.yml, config/core.entity_view_display.paragraph.text_and_image.image_align_left.yml, config/core.entity_view_display.paragraph.text_and_image.image_align_right.yml, config/core.entity_view_mode.media.original_resized.yml, config/responsive_image.styles.original_resized.yml
chore: media view mode for original resize, set responsive image styles to use full image style and update image and image and text paragraph type
Please see UNO-724 for more.
To test (optional):
1. Import config, drush image:flush
2. Visit `/news/afghan-women-aid-workers-risk-own-lives-keep-people-alive` and check that the images in the content area are no longer cropped
3. On any page, add a Text and Image paragraph and upload a diagram or another image with a non 3:2 aspect ratio. Make sure the whole image appears and there is no cropping.
Refs: UNO-724
=> UNO-724 Image and Image-and-Text image style should not crop

html/themes/custom/common_design_subtheme/templates/navigation/menu--main.html.twig
Refs: UNO-727
This fixes the IDs of the main navigation menu to ensure uniqueness.
1. Checkout the branch, clear the cache
2. Run `Object.entries(Array.from(document.querySelectorAll('[id]')).map(v => v.id).reduce((acc, v) => { acc[v] = (acc[v] || 0) + 1; return acc }, {})).filter(([key, value]) => value > 1).map(([ key, value]) => key);` in the browser console to get the list of duplicate IDs.
3. Confirm that there are none starting with `cd-nav` (main navigation).
=> [UNO-727] Fix ids of main navigation menu

docker/etc/nginx/custom/04_legacy_files.conf
Probably this one does work because location match precedence. The end result is the same, so whatevs.
Refs: OPS-9445
=> fix: Replace the legacy/ecosoc rule with one that works.

html/modules/custom/unocha_migrate/README.md, html/modules/custom/unocha_migrate/drush.services.yml, html/modules/custom/unocha_migrate/src/Commands/MigrateCommands.php
Refs: UNO-693
This adds a drush command to create or update redirects from CSV data (or single one with the `--source` and `--target` options).
The CSV data must be 2 columns:  source URL (legacy) and target URL (new URL). The URL can be relative ones in the from `/path` or full URLs (the domain doesn't matter).
=> [UNO-693] Drush command to create/update redirects

config/user.role.editor.yml
Refs: UNO-728
Allow editors to translate content and access the Canto API (via the video/image paragraph types).
=> [UNO-728] Update Editor role's permissions

config/core.entity_view_display.paragraph.figures.figures_compact_long.yml, config/core.entity_view_display.paragraph.figures.figures_compact_short.yml, html/modules/custom/unocha_utility/src/Helpers/NumberFormatter.php
Refs: UNO-739
This changes the precision for all the figures on the site to have only 1 decimal point.
1. Checkout the branch, clear the cache, import the condig
2. Visit pages with figures like `/our-funding`
3. Check that the figures are rounded to 1 decimal point
=> [UNO-739] Use one decimal point for the figures

html/themes/custom/common_design_subtheme/components/uno-layout/uno-layout.css, html/themes/custom/common_design_subtheme/css/styles.css, html/themes/custom/common_design_subtheme/templates/layouts/layout--fivecol.html.twig, html/themes/custom/common_design_subtheme/templates/layouts/layout--fourcol.html.twig, html/themes/custom/common_design_subtheme/templates/layouts/layout--threecol.html.twig, html/themes/custom/common_design_subtheme/templates/layouts/layout--twocol.html.twig
UNO-743 The render filter is being applied to the layout row, not the layout regions. This means we can still use a layout and leave the first region empty and it takes up space.
This also fixes an issue I introduced earlier which hid the RW images in places where we want them to show (Publications page)
=> UNO-575 Render layout row only if there is content

config/core.entity_form_display.paragraph.media_centre.default.yml, config/views.view.media_centre.yml, html/themes/custom/common_design_subtheme/css/styles.css, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--media-centre.html.twig
Refs: UNO-740
This PR changes the limit of the media collection items in the media centre block to 6 (from 5).
It also adds a new "archive" block that shows a paginated list of media collection items (12) like the "stories" view (no filters though).
Similar to the stories page, this block can be used on a basic page ("Media centre - Archive") with `/media-centre/archive` as path alias.
To go with that there is a template override for the `media-centre` paragraph type that displays a "view all" link to that archive page when not already on that page.
The "view all" link is styles the same
1. Normal deployment (cache clearing, config import)
2. Create a basic page with something like "Media centre - Archive" as title
3. Add a "media centre" paragraph type, select the "Archive" display
4. …
=> [UNO-740] Media centre - archive page

html/themes/custom/common_design_subtheme/components/uno-media/uno-media.css, html/themes/custom/common_design_subtheme/templates/fields/field--node--field-media-image--media-collection.html.twig
Refs: UNO-741
This PR adds a "data-count" attribute to the media photo galleries and uses it to adjust the size of the images:
=> [UNO-741] Photo galleries

html/themes/custom/common_design_claro/common_design_claro.theme, html/themes/custom/common_design_claro/templates/layouts/layout--fivecol--preview.html.twig, html/themes/custom/common_design_claro/templates/layouts/layout--fourcol--preview.html.twig, html/themes/custom/common_design_claro/templates/layouts/layout--threecol--preview.html.twig, html/themes/custom/common_design_claro/templates/layouts/layout--twocol--preview.html.twig, html/themes/custom/common_design_claro/templates/layouts/layout--twocol-66-33--preview.html.twig, html/themes/custom/common_design_claro/templates/layouts/layout--twocol-sidebar--preview.html.twig, html/themes/custom/common_design_subtheme/templates/layouts/layout--fivecol.html.twig, html/themes/custom/common_design_subtheme/templates/layouts/layout--fourcol.html.twig, html/themes/custom/common_design_subtheme/templates/layouts/layout--threecol.html.twig, html/themes/custom/common_design_subtheme/templates/layouts/layout--twocol.html.twig
Refs: UNO-743
*Please ignore the wrong reference to RW-743. It should read UNO-743. Was just doing 2 things a the same time...*
This PR does 2 things:
1. Add templates for the layouts (when used in a layout paragraph which is our use case) in the admin theme
2. Prevent rendering the content of the region twice but preserve the logic to display or not the rows based on whether the regions are empty or not.
This results in the original behavior from https://github.com/UN-OCHA/unocha-site/pull/257 for the frontend while preserving all the regions and rows in backend.
**Notes**
Empty regions only have the `#attributes` property. Non empty ones will have the `#attributes` property and at least one more for its content. So by checking the `length` we can determine if the region is empty or not. …
=> [UNO-743] Layouts

config/block.block.languageswitcher.yml, config/block.block.topmenu.yml, config/block.block.useraccountmenu.yml, config/core.extension.yml, html/themes/custom/common_design_subtheme/components/cd/cd.css, html/themes/custom/common_design_subtheme/templates/blocks/block--system-menu-block--account.html.twig
Refs: UNO-746
This shows the user menu when logged in (assuming here that we still don't want to show the "log in" link).
Note: the styling feels odd because of the css rules applied to the top header for the media centre:
URL aliases were created on preview (`/admin/config/search/path`):
- `/user/login` is an alias of `/saml/login`
- `/user/logout` is an alias of `/saml/logout`
When `saml` is not configured this is the equivalent of the normal login/logout.
1. Checkout the branch, clear the cache import the config
2. Log in, check that the user menu appears
3. In another browser/winder, as anonymous, check that the user menu is not there
4. Click the log out link and confirm you are logged out.
=> [UNO-746] Restore user menu when logged in

config/metatag.metatag_defaults.front.yml, config/system.site.yml
Refs: UNO-744
Ensures the twitter and facebook titles are not 'Homepage'.
=> [UNO-744] Fix homepage metatags

composer.patches.json, html/themes/custom/common_design_subtheme/components/uno-layout/uno-layout.css, html/themes/custom/common_design_subtheme/components/uno-mega-menu/uno-mega-menu.css, html/themes/custom/common_design_subtheme/templates/content/media-oembed-iframe.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--media-collection--full.html.twig
UNO-575
1. CKEditor patch to add scroll when viewing source
2. Mega menu height increase to accommodate another item under Europe without creating an additional column
3. Fix video scroll by adding overflow property to body tag in iframe template override
4. Move Image gallery above Body textarea for Media Collection
5. Adjust flex display for homepage to prevent overflow
=> UNO-575 More style improvements and CKEditor patch

html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--call-to-action.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--card-list--featured-highlight.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--card-list.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--card.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--node.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--subscribe.html.twig
Refs: UNO-753
This PR removes the `data-type` and `id` attributes in some paragraph templates copied from the response-site during the initial setup of the subtheme.
The `id` attribute interferes with the logic of the paragraph layout preventing it from adding the buttons to edit the paragraph.
I compared several pages with those paragraphs with prod and there is no impact. There doesn't seem to be any code in the subtheme necessitating those attributes so I think it's safe to remove them.
=> [UNO-753] Remove leftover attributes from paragraphs that impact backend

config/menu_breadcrumb.settings.yml, config/user.role.editor.yml, html/modules/custom/unocha_reliefweb/src/Form/BreadcrumbSettingsForm.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebBreadcrumbBuilder.php, html/modules/custom/unocha_reliefweb/unocha_reliefweb.links.menu.yml, html/modules/custom/unocha_reliefweb/unocha_reliefweb.permissions.yml, html/modules/custom/unocha_reliefweb/unocha_reliefweb.routing.yml, html/modules/custom/unocha_reliefweb/unocha_reliefweb.services.yml
Refs: UNO-760
This PR refactor the logic for the breadcrumb for the RW white labeled documents to use the breadcrumb of the parent path as base instead of having the breadcrumb fully hardcoded.
There is now an admin page `/admin/config/user-interface/reliefweb-breadcrumb` accessible via the configuration menu > ReliefWeb breadcrumb to adjust the paths. Editors have the permission to access this page.
After deploying:
1. Go to `/admin/config/user-interface/reliefweb-breadcrumb`
2. Set the default path to `/publications`.
3. Set the OCHA product paths to:
```
Press Release:/latest/press-releases
Statement/Speech:/latest/speeches-and-statements
```
2. Follow the after deployment instructions
3. Go to Latest > News and Stories > Press …
=> [UNO-760] Fix breadcrumb for RW white labeled documents.

docker/etc/nginx/custom/01_attachment_redirections.conf, docker/etc/nginx/custom/03_mapbox.conf, docker/etc/nginx/custom/04_legacy_files.conf
But only if no matching file exists on disk.
And pre-empt a load balancer IP change, which can cause nginx to proxy requests to the wrong addresses.
=> feat: Pass legacy file URLs to Drupal for Redirect module.

.github/workflows/composer-update.yml
Refs: updates
Updates produce a warning: `Unexpected input(s) 'php_version', valid inputs are ['github_access_token', 'patch_branch', 'patch_packages', 'patch_author', 'patch_maintainers', 'slack_bot_token', 'slack_channel_name', 'flowdock_token']`. The version is no longer needed.
https://github.com/UN-OCHA/unocha-site/actions/runs/5819534642
=> chore: remove unused variable

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module, html/themes/custom/common_design_claro/templates/paragraphs/paragraph--stories.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--stories.html.twig
Refs: UNO-765
This adds a check so that when there are no stories for a page (response, region, etc.) then the stories paragraph is not displayed.
However for the form, we still want to show the paragraph so this alters the template and adds a 'No stories currently for this page.' message if there are no stories.
If a `stories` paragraph is added to a response for which there are no stories tagged with it **and** the response is under a region or another menu item that doesn't have stories either, then the `stories` paragraph will be empty.
Same thing when adding a `stories` paragraph to an existing region without stories tagged with this region.
That means that to be able to show stories for the `response-template` page, at least one **demo/dummy** story tagged with the …
=> [UNO-765] Prevent error when there a no stories to show in a stories paragraph type

html/themes/custom/common_design_claro/templates/views/views-view.html.twig
replace views template to remove the exposed filter dropdown so it is not used in the admin theme
Refs: UNO-609
=> UNO-609 replace views template to remove the exposed filter dropdown

config/core.entity_form_display.paragraph.news_and_stories.default.yml, config/views.view.stories.yml, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-768
This PR changes the name of the exposed filters for the News and Stories view to "countries", "responses" and "regions" instead of "country", "response" and "region".
It happened that the "region" query parameter has a special meaning for the layout paragraphs to determine where to place the paragraph when adding a new one.
The exposed "region" filter from the news and stories was conflicting when adding such a paragraph type and was set to an empty string which was not a valid option.
1. Checkout the branch, clear the cache and import the config
2. Add a "news and stories" paragraph to some content, it should show the default latest list (or whatever display was selected)
3. Save, there should be no error message anymore
4. Visit a region, check that the "view all" for the …
=> [UNO-768] Fix issue with news and stories

config/views.view.content.yml, config/views.view.media.yml
Refs: UNO-766
This removes the filter for the `/admin/content` view that limits to published content if not an admin so that editors can see all the content published or unpublished and whether they are the author or not.
Same thing for `/admin/content/media`.
Note: editors already have the permission to view other unpublished content or media but the /admin/content views didn't respect that.
See https://www.drupal.org/project/drupal/issues/2971902 for similar issue.
2. Log in as an editor, create some page
3. Log in as a **different** editor in another browser or private tab and check that you see the page from (1) and can access it.
=> [UNO-766] Allow editors to view other unpublished content

docker/etc/nginx/custom/01_attachment_redirections.conf, html/modules/custom/unocha_reliefweb/src/Controller/ReliefWebDocumentController.php, html/modules/custom/unocha_reliefweb/src/Services/ReliefWebDocuments.php, html/modules/custom/unocha_reliefweb/templates/unocha-reliefweb-entity-image.html.twig, html/modules/custom/unocha_reliefweb/templates/unocha-reliefweb-river-article--report.html.twig, html/modules/custom/unocha_reliefweb/unocha_reliefweb.module, html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css, html/themes/custom/common_design_subtheme/templates/modules/unocha_reliefweb/unocha-reliefweb-entity-image.html.twig
Refs: UNO-771
This PR adds the display of the report image on the RW whitelabeled document pages.
Screenshot source: https://unocha-local.test/publications/report/occupied-palestinian-territory/determined-stay-umm-salehs-unyielding-stand-amid-settler-aggression (replace unocha-local.test with your local domain).
The image is currently displayed like on RW, below the title. The image is a bit scaled up (700px -> 820px).
There are few `@todo ... (UNO-771)` if we decide to add a large image style on RW (ex: `extra-large` (1400px)).
1. Checkout the branch, clear the cache, import the config.
2. Visit the URL mentioned above, the image should appear.
=> [UNO-771] Display report image for RW documents

config/core.extension.yml, config/language/ar/views.view.moderated_content.yml, config/language/es/views.view.moderated_content.yml, config/language/fr/views.view.moderated_content.yml, config/language/ru/views.view.moderated_content.yml, config/language/zh-hans/views.view.moderated_content.yml, config/user.role.editor.yml, config/views.view.media.yml, config/views.view.moderated_content.yml, html/modules/custom/unocha_menus/unocha_menus.module
Refs: UNO-775
This PR allows editors to view and edit any unpublished content or media by enabling the content_moderation module as described in https://www.drupal.org/docs/7/managing-users/viewing-unpublished-content#s-drupal-9
Note: the `Moderated content` view is disabled because, we only use the basic workflow with published/unpublished.
2. Log in as an editor, create some dummy node, save it as unpublished (uncheck "published" above the save button)
3. Check that it's not accessible to anonymous users or authenticated users without the `Editor` role
4. Log in as a different editor, check that the content from (2) appears in `/admin/content` and can be edited
5. Edit it, change the title for example and save it as published
6. …
=> [UNO-775] Allow editors to view and edit any unpublished content or media

config/views.view.content.yml, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-773
This PR renames `sticky` to `featured` and hide promote to front page.
1. Checkout the branch, clear the cache and import the config
2. Edit a node, check that under "Promote options" only "Featured" appears.
3. Go to /admin/content, check that the options in the bulk operations at the bottom are `Make content featured`.
=> [UNO-773] Rename sticky to featured and hide promote to front page

html/themes/custom/common_design_subtheme/components/uno-river/uno-river.css, html/themes/custom/common_design_subtheme/css/styles.css
move rules related to RW River from styles and into its component, group layout specific rule together, prefix rule for header flex 100% with layout class and remove `rw-river-article--with-preview` selector so it applies to all RW River items
Refs: UNO-776
This PR fixes the issue below, where the item did not span the full available width:
Eg. https://www.unocha.org/niger
=> UNO-776 Fix width for river item in Resources

html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--section--default.html.twig
chore: section paragraph override with section element so default view mode is more self-explanatory
Refs: UNO-575
=> UNO-575 Make Section paragraph Default view mode display as section element

docker/etc/nginx/custom/04_legacy_files.conf
Refs: UNO-693
This adds a catch all `/sites/` location nginx rule and adds the relevant sub location rules to handle current site and legacy files including weird ones like `dms/Documents/xxx`.
It copies some parts of some rules for files from https://github.com/UN-OCHA/docker-images/blob/main/php/php-k8s-v82/etc/nginx/apps/drupal/drupal.conf so that site files (uploaded files, images, aggregated css/js and image derivatives) are handled as "usual" with the exception of the requests always being passed to Drupal regardless of the environment if the file is not find on disk (except for derivative images).
It also contain the rule for legacy and ECOSOC files.
Hopefully this is a bit easier to maintain that a modified copy of the `drupal.conf` file.
This was tested with the following:
- …
=> [UNO-693] Add nginx rules to handle legacy file URLs redirections

html/themes/custom/common_design_subtheme/templates/modules/unocha_donors/unocha-donors-list--oct-top-donors.html.twig, html/themes/custom/common_design_subtheme/translations/ar-common-design.po, html/themes/custom/common_design_subtheme/translations/es-common-design.po, html/themes/custom/common_design_subtheme/translations/fr-common-design.po
Refs: UNO-780
Apparently the base FTS url redirects to the current year's funding page (https://fts.unocha.org --> https://fts.unocha.org/home/2023/donors/view).
=> [UNO-780] Use base FTS URL which redirects to the current year page

html/themes/custom/common_design_subtheme/components/uno-section-tabs/uno-section-tabs.js
chore: use id from anchor for tab to prevent duplicate IDs when multiple tab sets are on the same page
This came up during recent accessibility testing.
Before: Each Section Tabs has Tabs (anchor elements) with IDs 1, 2, 3 etc
After: Each Section Tabs has unique IDs using the `paragraph.id()`
1. Before checking out this branch, visit a page with multiple Section Tabs paragraphs, like a Response.
2. Notice the markup for the anchors, specifically the ID: `<a href="#section--84" id="tab1" role="tab" aria-selected="true">Overview</a>`
4. Searching the markup for the ID `tab1` should return multiple IDs.
5. Check out this branch, clear cache.
6. Look at the Section Tabs again and notice the change in markup, where the ID is now unique: <a href="#section--84" id="#tab--84" role="tab" …
=> UNO-784 Prevent duplicate IDs on Section Tabs

html/themes/custom/common_design_subtheme/components/cd/cd.css, html/themes/custom/common_design_subtheme/templates/blocks/block--system-branding-block.html.twig, html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-footer.html.twig, html/themes/custom/common_design_subtheme/templates/uno/subscribe--global.html.twig
See UNO-784
1. Prevent Duplicate IDs on Response and Region pages that have their own Mailchimp subscription form, by copying the subscribe twig partial and appending `--global` to IDs.
2. Add "logo" to logo alt text
3. Set nav h2 colour to avoid colour contrast issues in Check1st scans
=> UNO-784 Accessibility improvements

config/core.entity_form_display.paragraph.stories.default.yml, config/core.entity_view_display.media.image.featured.yml, config/core.entity_view_display.node.story.featured.yml, config/core.entity_view_display.paragraph.stories.cards.yml, config/core.entity_view_display.paragraph.stories.cards_with_featured.yml, config/core.entity_view_mode.media.featured.yml, config/core.entity_view_mode.node.featured.yml, config/core.entity_view_mode.paragraph.cards_with_featured.yml, config/field.field.paragraph.stories.paragraph_view_mode.yml, config/responsive_image.styles.card.yml, config/responsive_image.styles.featured.yml, html/modules/custom/unocha_paragraphs/unocha_paragraphs.module, html/modules/custom/unocha_paragraphs/unocha_paragraphs.post_update.php, html/themes/custom/common_design_subtheme/components/uno-stories/uno-stories.css, html/themes/custom/common_design_subtheme/templates/content/node--story--card--featured.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--stories.html.twig
Refs: UNO-785
This PR does the following:
1. Adds a `featured` responsive image style with the image styles from the `card` responsive image style
2. Changes the `card` responsive image style to use smaller image styles on large screens
3. Adds a `featured` view mode for `image media` using the above `featured` responsive image style
4. Adds a `featured` view mode for `story nodes` using the above `featured` media view mode
5. Adds `cards with featured` view mode for `stories paragraphs`
6. Adds the `parapraph view mode` field for `stories paragraphs`, defaulting to `cards` and with `cards with featured` as second option
7. Changes a bit the logic for the preprocess function of the `stories paragraphs` to use the `featured` view mode and the `node__story__card__featured` theme for the …
=> [UNO-785] Featured story

composer.json, composer.lock, config/core.extension.yml, config/user.role.editor.yml
feat: samples module for demo content, install, enable, set perms
See OPS-9689
Refs: OPS-9689 UNO-762
1. Check out the branch, run composer install, and import config to install and enable the module. You might need to rebuild permissions `https://unocha-local.test//admin/reports/status/rebuild`
2. Visit a sample content page Eg. https://unocha-local.test/demo - Notice it is unpublished.
3. Edit it. Check the "Use as a sample" checkbox and also Publish
4. Visit the page in a private browser or logged out and you should get an Access denied message.
=> OPS-9689 Samples module for demo content

html/modules/custom/unocha_paragraphs/unocha_paragraphs.deploy.php
Refs: OPS-9693
Use hook_deploy_NAME instead of hook_post_update_NAME since we use drush deploy for deployments otherwise the config import is done too late and the paragraph view mode field cannot be initialized.
See: https://www.drush.org/12.x/deploycommand/
1. Checkout the branch 
2. Import a DB dump (`drush sqlc < dump.sql`)
3. Clear the cache (`drush cr`)
4. Deploy (`drush deploy`)
5. There should be something like:
```
------------------- --------------- ------------------------------------------ 
Module              Hook            Description                               
------------------- --------------- ------------------------------------------ 
unocha_paragraphs   stories_parag   Implements hook_deploy_NAME().   Change   
raph_view_mod   the view mode of the stories …
```
=> [OPS-9693] Deployment fix

html/themes/custom/common_design_subtheme/common_design_subtheme.theme
fix: json linked data script to set WebSite name
See OPS-9695
1. Check out branch, clear cache
2. Visit homepage https://unocha-local.test/ and confirm the following script appears in the`<head>`:
3. `<script type="application/ld+json">{"@context" : "https://schema.org", "@type" : "WebSite", "name" : "UN OCHA", "url" : "https://www.unocha.org"}</script>`
4. Visit an internal page and confirm the script does not load on internal pages.
=> OPS-9695 Fix site name display in Google search results

docker/etc/nginx/custom/03_mapbox.conf
Refs: OPS-9699
This substitutes the mapbox token in the proxied mapbox responses.
1. Checkout the branch
2. Recreate the drupal container
3. Visit the homepage
4. Check the network tab (refresh if necessary), filter by `mapbox`
5. Check the content of any json file, the mapbox token should not be present (instead there should be `access_token=token`)
=> [OPS-9699] Remove mapbox token from mabox responses

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-785
Ensure we use a different cache key based on the story view mode.
**Before checking out**
1. Enable caching for your local (edit the `./local/shared/settings/settings.local.php`, replace `$no_cache = TRUE;` with `$no_cache = FALSE;`)
2. Import dump (`unocha-prod-2023-10-05.2048.sql.gz`)
3. Clear the cache
4. Visit `/latin-america-and-caribbean` (this will cache the `Today's top news: Sudan, Ukraine, CERF allocation, Syria` rendered as `featured` (large card))
5. Visit the `/asia-and-pacific`, the same story will still be rendered as featured while it should not.
6. Clear the cache
7. Do the opposite and visit `/asia-and-pacific` first, the story should be rendered as a small card
8. Visit  `/latin-america-and-caribbean`, should also be rendered as a small card instead of the …
=> [UNO-785] Fix stories caching

html/themes/custom/common_design_subtheme/components/uno-response-map/uno-response-map.css, html/themes/custom/common_design_subtheme/components/uno-river/uno-river.css, html/themes/custom/common_design_subtheme/css/brand.css
I searched the files and markup for `.unocha-response-map__title` and I get the impression this selector is not in use, so I think the declaration I commented out will not have any negative repercussions. It was the only place `--brand-highlight-contrast: #000;` was being used.
=> UNO-784 Colour contrast for tags in RW river when on grey background

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-785
In forms, paragraphs are rendered with the `preview` view mode. This alters the logic for the stories paragraphs to check the `paragraph_view_mode` field to determine how to render the first node when the paragraph view mode is `preview`.
Note: this is a PR against the branch of https://github.com/UN-OCHA/unocha-site/pull/367.
1. Checkout the branch, clear the cache.
2. Repeat the `tests` from https://github.com/UN-OCHA/unocha-site/pull/365 to confirm that there are no regressions
3. Edit a for example, **in the form** check that the first story uses the `featured` view mode when the stories paragraph view mode is `cards with featured` and uses the `card` view mode when the paragraph view mode is `cards`.
=> [UNO-785] Stories paragraph view mode in forms

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-790
This ensures that the nodes associated with menu links are returned in the order of the menu links.
**Before checking out**
1. Go to `/admin/structure/menu/manage/main`
2. Change the order of the menu items under `Somalia`, for example by putting the node with the highest ID first (ex: `contacts`)
3. Check the `Resources` tab in the `/somalia` page and confirm the order doesn't reflect the order of the menu items
**After checking out**
1. Clear the cache
2. Repeat (2) and (3) above, this time the order of the resources should match the order in the menu.
=> [UNO-790] Return nodes associated with menu links in the menu links order

html/themes/custom/common_design_subtheme/templates/content/node--basic--card.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--card.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--event--card.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--media-collection--card.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--region--card.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--response--card.html.twig, html/themes/custom/common_design_subtheme/templates/content/node--story--card.html.twig
See screenshot on UNO-792
Adjust Card template override so the card image div and anchor print only when the image is present.
1. Visit the Prod site https://www.unocha.org At the moment, there is an item present that does not have an image.
2. Notice the markup includes `.uno-card__image` div and an empty anchor within it.
3. Check out branch, clear cache.
4. Visit https://unocha-local.test/
5. Select a Story node that displays in the Latest News and Stories block and remove its image. Save the node and refresh the homepage.
6. Notice the markup not longer includes the `.uno-card__image` div or the anchor
7. Notice the other stories with image display as usual and the image is still linked.
All Content Types with Card template overrides have been adjusted. I've used the content examples …
=> UNO-792 Prevent empty anchors on Cards

html/themes/custom/common_design_claro/css/styles.css
See UNO-789 for screenshots
1. Increase height of modal for Canto
2. Style the "Sample content" checkbox from Samples module - see also https://github.com/UN-OCHA/unocha-site/pull/384
=> UNO-789 Content Editor UI improvements

config/user.role.editor.yml
Reduce Editor role access to Sample content. They can view and edit, but not manage which means Editors never have to see the checkbox.
This is complimentary to the styling here https://github.com/UN-OCHA/unocha-site/pull/369
Refs: UNO-800
=> UNO-800 Sample content should be managed by admin role only

html/themes/custom/common_design_subtheme/components/uno-section-tabs/uno-section-tabs.js
As mentioned here https://github.com/UN-OCHA/unocha-site/pull/291#pullrequestreview-1705790743
chore: prevent i is not defined when keying through section tabs
Refs: UNO-806
=> UNO-806 Prevent i is not defined when keying through section tabs

PATCHES/entity_browser-php82-3350169.patch, composer.json, composer.lock, composer.patches.json, config/core.entity_form_display.paragraph.stories.default.yml, config/core.entity_view_display.node.story.card_preview.yml, config/core.entity_view_mode.node.card_preview.yml, config/core.extension.yml, config/entity_browser.browser.stories.yml, config/samlauth.authentication.yml, config/user.role.editor.yml, config/views.view.entity_browser_stories.yml, html/themes/custom/common_design_claro/css/styles.css, html/themes/custom/common_design_claro/templates/content/node--story--card-preview.html.twig
Refs: UNO-802
This PR adds the `entity_browser` module and related view to offer somehow a better UX to select the featured stories:
The display of the selected stories in the paragraph widget needs some styling however:
**Notes**
It's not possible to re-order the selected stories, they need to be removed and re-added one by one. Maybe that's fine if there are only 2 or 3 of them.
Currently the selected stories only show their label but they can be rendered with a view mode (widget setting in `/admin/structure/paragraphs_type/stories/form-display`) so we could define a new view mode (notably to have a template where we could add the  `target="_blank"` attribute to the links to not leave the form).
=> [UNO-802] Better UX to select featured stories

config/core.entity_form_display.paragraph.section.default.yml, config/core.entity_view_display.paragraph.section.container.yml, config/core.entity_view_display.paragraph.section.default.yml, config/core.entity_view_display.paragraph.section.tabs.yml, config/field.field.paragraph.section.field_text.yml, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--section--default.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--section--tabs.html.twig
Refs: UNO-807
This adds the common `field_text` to the `section` paragraph type and update the corresponding templates.
2. Edit a response
3. Edit a section paragraph
4. Check that the text field appears
5. Enter some text
6. Save then save the node form
7. Confirm that the text appear above the content of the section
8. Repeat (5) to (7), using a different view mode for the section parapragh
=> [UNO-807] Add text field to section paragraphs

config/filter.format.ckeditor.yml, html/modules/custom/unocha_utility/src/Plugin/Filter/ExternalLinkFilter.php, html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/uno-external-links/README.md, html/themes/custom/common_design_subtheme/components/uno-external-links/uno-external-links.css
Refs: UNO-807
This adds text filter that adds the `target` and `rel` attibutes to external links. It also adds the library to style those external links.
Note: this is against the UNO-807 branch.
2. Edit a response for example, add a text paragraph type
3. Enter a link to an external site
4. Enter an internal link (either with the domain of your local instance or unocha.org or www.unocha.org)
5. Save then save the node
6. Check that the link from (3) has an icon and the link from (4) doesn't.
=> [UNO-807] Add icon after external links

html/themes/custom/common_design_subtheme/components/uno-node/uno-node.css
Refs: UNO-807
Adjust the margin bottom for the text field inside a section paragraph type. Handle nested section paragraphs as well.
**Before**
**After**
1. Checkout the branch, clear the cache
2. Edit the `/afghanistan` for example, add a text to the `Overview of the Humanitarian Response in Afghanistan` section paragraph.
3. Add a text to the `Humanitarian Needs Overview` sub section
4. Save
5. Confirm that the result is like in the screenshot.
=> [UNO-807] Adjust bottom margin of text field inside section paragraph

html/themes/custom/common_design_subtheme/components/uno-stories/uno-stories.css
chore: set flex on title for full width display when title is short
Refs: UNO-796
To test:
See UNO-796 for before screenshot.
Check out branch and clear cache.
Visit the homepage and edit the title of the first item in Latest News and Stories to reduce the number of words to just a few.
Notice the title element takes up the available width, no longer dependent on the specific content.
Expected result:
=> UNO-796 Title should display full width even if it is short

html/themes/custom/common_design_subtheme/components/rw-entity-meta/rw-entity-meta.css, html/themes/custom/common_design_subtheme/components/uno-document/uno-document.css, html/themes/custom/common_design_subtheme/components/uno-river/uno-river.css, html/themes/custom/common_design_subtheme/templates/modules/unocha_reliefweb/unocha-reliefweb-river-article--report.html.twig
UNO-787
I've removed Format and Posted data from the template overrides and also the CSS rules that hid them.
We should be using Published for the date, so this replaces Posted in some cases, so the CSS selectors are updated to suit.
After checking out this branch, compare any pages that have Reliefweb Document or River Paragraphs. All elements in the Document or Report items should appear unchanged as this is a refactor.
Example pages:
- https://demo.unocha-org.ahconu.org/demo/reliefweb-rivers
- https://demo.unocha-org.ahconu.org/demo/page-components
- https://demo.unocha-org.ahconu.org/ocha
- Any Response page https://demo.unocha-org.ahconu.org/myanmar
I ran VRT between my local with this branch and the demo site and all good.
=> UNO-787 RW Report template override refactor

composer.json, composer.lock, config/core.extension.yml, config/honeypot.settings.yml
Refs: UNO-809
This adds the honeypot module and configures it for the contact us form.
1. Checkout the branch, rebuild the image, clear the cache and import the config
2. Go to the contact us page and inspect the page to confirm the `honeypot_time` fields is there
3. Fill in the form, send and check mailpit (ex: http://mail.unocha-local.test) to confirm the email was sent
4. Return to the contact us form, inspect the page, search for the `form-wrapper` element with `style="display: none !important;"`, remove the style attribute to reveal the honeypot input field
5. Fill in the form including the field above
6. Send and confirm there is an error message and and a log message in the DB logs
=> [UNO-809] Add honeypot to contact form

config/core.extension.yml, config/language/ar/views.view.user_admin_people.yml, config/language/es/views.view.user_admin_people.yml, config/language/fr/views.view.user_admin_people.yml, config/language/ru/views.view.user_admin_people.yml, config/language/zh-hans/views.view.user_admin_people.yml, config/system.action.user_add_role_action.user_manager.yml, config/system.action.user_remove_role_action.user_manager.yml, config/user.role.user_manager.yml, config/views.view.user_admin_people.yml, html/modules/custom/unocha_users/README.md, html/modules/custom/unocha_users/src/UserPermissions.php, html/modules/custom/unocha_users/unocha_users.info.yml, html/modules/custom/unocha_users/unocha_users.module, html/modules/custom/unocha_users/unocha_users.permissions.yml
Refs: UNO-810
This PR adds a module with granular permissions to manager user accounts and a `User manager` role that can change roles and block user accounts.
A person with the `User manager` role can see the list of people (`/admin/people` page), edit their accounts and change the account status and the roles:
1. Checkout the branch, import the config, clear the cache
2. Log in as an `authenticated` user, check you cannot access `/admin/people` and check you cannot access another account's form (ex: `user/5/edit`)
3. Log in as an editor, check it's the same as (2)
4. Log in as a `Administrator`, check that you have access to `/admin/people` and can edit another account's form and can see all the fields (display name, mail etc.)
5. Assign the `User manager` role to a non-administrator …
=> [UNO-810] User management

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module, html/themes/custom/common_design_claro/templates/paragraphs/paragraph--reliefweb-river.html.twig
Refs: UNO-817
This does 2 things:
It adds a theme suggestion to have more granularity with the templates for the paragraph with a `view mode` field.
So for example, one could create a `paragraph--reliefweb-river--preview--resources.html.twig` template for "reliefweb river" paragraph types with the "resources" view mode to use when displayed in the form ("preview" view mode).
It also adds a class in the claro subtheme's "reliefweb river" paragraph template to help with the styling:
**Note:** the class addition above applies to all the reliefweb river paragraphs. To only add the class to the `resources` view mode, one can create a `paragraph--reliefweb-river--preview--resources.html.twig` in the claro subtheme and copy the code from `paragraph--reliefweb-river.html.twig` and remove the …
=> [UNO-817] Paragraph view mode theme suggestion

html/modules/custom/unocha_paragraphs/unocha_paragraphs.module
Refs: UNO-827
This ensures the ordering of the menu links for example in the resources paragraphs is the same as the order in the menu UI: first ordered by weight then title if same weight.
**Before checking out this branch**
1. Import recent dump
2. Visit `/west-and-central-africa` for example, take note of the order (see ticket as well), the order should show something like "Allocation..." then "About...".
**After checking out this branch**
1. Checkout the branch, clear the cache
2. Visit `/west-and-central-africa` and confirm that the order is as expected ("About..." before "Allocation...")
=> fix: order menu links by weight and title

config/field.field.node.basic.field_custom_content.yml, config/field.field.node.event.field_custom_content.yml, config/field.field.node.media_collection.field_custom_content.yml, config/field.field.node.region.field_custom_content.yml, config/field.field.node.resource.field_custom_content.yml, config/field.field.node.response.field_custom_content.yml, config/field.field.node.story.field_custom_content.yml
Refs: UNO-824
No change in functionality. This simply sync the field_custom_content config from DB to code. It mostly updates the list of paragraph types that can be include/excluded. The config files contained old paragraph types from the dev stage. Only the media collection node type actually limits the selection of paragraph types.
=> [UNO-824] Update outdated field_custom_content config

composer.json, composer.lock
Refs: OPS-10039
It has not been enabled for a long time - now there's a security issue
too.
=> chore: remove google_tag module

CHANGELOG.md, composer.json, composer.lock
* Update all outdated drupal/* unocha/* drush/* weitzman/drupal-test-traits packages. ([72b711](https://github.com/UN-OCHA/unocha-site/commit/72b7115cb24544190d3b867fe408d322b4605f86))
| Production Changes            | From    | To      | Compare                                                                         |
|-------------------------------|---------|---------|---------------------------------------------------------------------------------|
| aws/aws-sdk-php               | 3.342.4 | 3.342.9 | [...](https://github.com/aws/aws-sdk-php/compare/3.342.4...3.342.9)             |
| drupal/core                   | 10.4.4  | 10.4.5  | [...](https://github.com/drupal/core/compare/10.4.4...10.4.5)                   |
| drupal/core-composer-scaffold | 10.4.4  | 10.4.5  | …
=> Deploy 21-03-2025
